import sys; sys.path.insert(0,'tools')
import policy_builder as B
P="policy_library/"
spec={
 "title":"Access Control Policy","path":P+"Access_Control_Policy.docx",
 "purpose":"This policy establishes the rules governing who may access [Organization Name]'s systems, networks, and Controlled Unclassified Information (CUI), and what those individuals may do once access is granted. Unauthorized or excessive access is one of the leading causes of data breaches and compliance violations. By enforcing strict account management, least privilege, and session controls, this policy reduces the risk that CUI is accessed, modified, or disclosed without authorization — whether by insiders, compromised credentials, or third parties.",
 "scope":["All employees, contractors, consultants, vendors, and any other individuals who access organizational systems or data.","All information systems owned, operated, or managed by [Organization Name], including cloud services, on-premises servers, endpoints, mobile devices, and operational technology that process, store, or transmit CUI.","Third-party systems that connect to organizational networks or handle CUI on the organization's behalf."],
 "scope_tail":"Where CUI is involved, requirements are non-negotiable and supersede convenience or operational preferences.",
 "definitions":[
   ("Account","A user identity (username + credential) that grants access to a system or application."),
   ("Least Privilege","Giving a user only the minimum access needed to perform their job — nothing more."),
   ("Privileged Account","An account with elevated rights (e.g., administrator, root, system account) that can configure systems, manage other accounts, or override controls."),
   ("Separation of Duties (SoD)","Splitting critical tasks between two or more people so no single person can commit fraud or make a critical error undetected."),
   ("Multi-Factor Authentication (MFA)","Requiring two or more independent proofs of identity (e.g., password + phone code) before granting access."),
   ("Session Lock","Automatically hiding screen content and requiring re-authentication after a period of inactivity."),
   ("Remote Access","Connecting to organizational systems from outside the organization's physical premises."),
   ("MDM (Mobile Device Management)","Software that enforces security policies on smartphones and tablets."),
   ("External System","Any computer system not owned or controlled by [Organization Name], including personal computers and cloud services not authorized in the SSP."),
 ],
 "roles":[
   ["[IT Manager / ISSO]","Own this policy; approve accounts and privileges; review access quarterly; maintain the account inventory; report violations."],
   ["[System Administrator]","Implement access controls in systems; execute provisioning and de-provisioning; generate and retain access logs."],
   ["[Human Resources]","Notify IT within [1 business day] of new hires, role changes, and terminations to trigger account actions."],
   ["[Department Manager / Supervisor]","Authorize access requests for their team; confirm least-privilege assignments; approve exceptions within their scope."],
   ["All Users","Use only the accounts and privileges assigned to them; report suspected unauthorized access immediately."],
   ["[Senior Leadership / CISO]","Approve policy; review compliance metrics; accept residual risk for documented exceptions."],
 ],
 "statements":[
   ("PS-1  Account Authorization","All user and service accounts must be formally authorized by an account owner before being created. Authorization must be documented (e.g., a signed access request form or ticket). A complete inventory of all accounts — including their type, owner, and access level — must be maintained and kept current at all times."),
   ("PS-2  Account Types","The organization must define and enforce distinct account types (individual user, service/shared, privileged/administrator, guest). Shared accounts are prohibited on systems that process CUI unless technically unavoidable and explicitly approved with compensating controls documented in the SSP."),
   ("PS-3  Least Privilege","Each account must be provisioned with only the minimum permissions required to perform the user's assigned job function. Access rights must be reviewed [organization-defined: at least quarterly; recommended: quarterly], and any excess privileges removed within [organization-defined: 5 business days; recommended: 5 business days] of discovery."),
   ("PS-4  Separation of Duties","Critical or high-risk functions — such as financial transactions above a defined threshold, code promotion to production, and account provisioning — must be divided so that no single individual can complete the action alone. The organization must document which functions require SoD and maintain an up-to-date role matrix."),
   ("PS-5  Privileged Account Controls","Privileged accounts must be separate from standard user accounts. Privileged access must not be used for routine activities (e.g., reading email, browsing the web). Use of privileged accounts must be logged. The number of privileged accounts must be limited to the minimum necessary."),
   ("PS-6  Access Termination and Transfer","When an individual leaves the organization or changes roles, their access must be reviewed and adjusted within [organization-defined: 1 business day for termination, 5 business days for role change; recommended: same-day for termination]. HR must notify IT of personnel changes within 1 business day."),
   ("PS-7  Remote Access Controls","Remote access to organizational systems must be authorized, encrypted using [organization-defined: TLS 1.2 or higher; VPN with AES-256; recommended: TLS 1.3 or VPN with AES-256], and protected by MFA. Remote access sessions must be monitored. Users must not route organizational traffic through unapproved networks or devices. Remote-access permissions must be reviewed [organization-defined: annually; recommended: annually]."),
   ("PS-8  Remote Access via External Networks","Users connecting from external or public networks (e.g., hotel Wi-Fi, coffee shops) must use the organization's approved VPN or secure remote-access gateway for all traffic to organizational systems. Split-tunneling configurations that allow simultaneous access to the internet and organizational systems are prohibited on systems processing CUI unless explicitly approved."),
   ("PS-9  Session Lock","Systems must be configured to automatically lock the screen after no more than [organization-defined: 15 minutes; recommended: 15 minutes] of inactivity. Re-authentication must be required to unlock the session. Users must manually lock their sessions whenever they leave their workstation unattended."),
   ("PS-10  Session Termination","Systems must automatically terminate idle sessions after [organization-defined: 30 minutes for high-privilege sessions, 60 minutes for standard sessions; recommended: 30 / 60 minutes]. After termination, the user must fully re-authenticate to resume work."),
   ("PS-11  Wireless Access","Wireless network connections must be authorized before use. Wireless networks used to transmit CUI must use [organization-defined: WPA3-Enterprise or WPA2-Enterprise with AES-CCMP; recommended: WPA3-Enterprise]. Guest wireless networks must be logically separated from networks that carry CUI. Rogue wireless access points must be detected and reported immediately."),
   ("PS-12  Mobile Device Use","Mobile devices (smartphones, tablets, laptops) used to access organizational systems or CUI must be enrolled in the organization's [organization-defined: MDM solution; recommended: Microsoft Intune or equivalent] before use. MDM must enforce encryption, screen lock, remote wipe, and approved-application policies."),
   ("PS-13  Mobile Device Restrictions","CUI must not be stored on personal mobile devices unless those devices are enrolled in MDM and meet all security requirements. Jailbroken or rooted devices must never be used to access organizational systems or CUI. Users must report lost or stolen devices within 4 hours of discovery so that a remote wipe can be initiated."),
   ("PS-14  External Systems","Users must not access, process, store, or transmit CUI on personally owned computers or any system not explicitly authorized in the SSP without a documented approval from the policy owner. Before any external system is permitted to connect to organizational systems, a use agreement and security review must be completed and retained on file."),
 ],
 "procedures":[
   ("6.1  Account Lifecycle",["New hire: HR submits access request to IT within 1 business day of start date.","IT verifies manager approval, creates account with least-privilege permissions, and documents in the account inventory.","User completes security awareness training before CUI access is granted.","Role change: Manager submits updated access request; IT adjusts rights within [5 business days].","Termination: HR notifies IT same day; IT disables account, revokes remote access, and removes CUI access within [1 business day]."],"Completed access request forms or tickets; account inventory (dated); termination checklists; training completion records."),
   ("6.2  Privileged Account Management",["Privileged accounts must be listed and reviewed [quarterly].","Admin actions must be logged to a tamper-resistant log store.","Shared privileged credentials must use a password vault; passwords rotated after each use."],"Privileged account list; quarterly review sign-offs; password vault access logs."),
   ("6.3  Access Reviews",["The IT Manager conducts a formal access review [quarterly] for all CUI systems.","Reviewers certify that each account's access is still needed and appropriately scoped.","Excess access is removed within [5 business days] of review completion."],"Dated access review reports signed by the IT Manager; evidence of remediation actions."),
   ("6.4  Remote Access & Session Controls",["VPN and remote-access gateway configurations reviewed annually for compliance with PS-7.","Session lock and termination enforced via GPO or MDM and verified during [quarterly] configuration audits.","MFA enrollment verified for all remote-access users."],"VPN configuration exports; GPO/MDM screenshots; MFA enrollment reports; configuration audit logs."),
   ("6.5  Wireless & Mobile",["Wireless configurations reviewed [annually] or after any network change.","MDM enrollment status verified monthly; non-enrolled devices blocked.","Lost-device reports logged; remote wipe initiated and confirmed."],"Wireless configuration records; MDM enrollment reports; remote-wipe confirmation records."),
   ("6.6  External System Use",["Any request to use an external system for CUI is submitted to the IT Manager.","The IT Manager completes a security review and issues a written authorization or denial.","Users sign an external-system use agreement before access is granted."],"External-system request forms; security review records; signed use agreements."),
 ],
 "compliance_focus":"through log reviews, access-review reports, and configuration audits, covering account authorization, least privilege, remote access, and session controls.",
 "related":["System Security Plan (SSP) — authoritative system inventory, CUI categories, and control implementation details.","Incident Response Policy — procedures when unauthorized access is detected.","Configuration Management Policy — baseline hardening standards that complement session-control requirements.","Identification and Authentication Policy — password, MFA, and credential-management requirements.","Personnel Security Policy — background screening and onboarding/offboarding procedures.","Audit and Accountability Policy — logging, monitoring, and log-retention requirements."],
 "mapping_intro":"The table below maps each required control to the policy statement(s) that satisfy it and the evidence an auditor will seek. Control IDs are from NIST SP 800-171 Rev 3 (family 03.01); they are equally applicable to CMMC 2.0 Level 2 and ITSP.10.171 (CPCSC).",
 "mapping":[
   ["03.01.01  Account Management","PS-1, PS-2, PS-3 — authorized access; account types; least privilege","Account inventory; access request forms; provisioning records"],
   ["03.01.02  Access Enforcement","PS-2, PS-5 — central enforcement; privileged controls","Access-enforcement configuration; privileged-action logs"],
   ["03.01.04  Separation of Duties","PS-4 — separation of duties","Role matrix showing SoD"],
   ["03.01.05  Least Privilege","PS-3, PS-5 — least privilege; privileged restrictions","Privileged account list; access review reports"],
   ["03.01.06/07  Least Privilege – Privileged Accounts/Functions","PS-5 — privileged account/function control","Privileged account list; privileged-function logs"],
   ["03.01.08  Unsuccessful Logon Attempts","PS-5, PS-7 — lockout/throttling","Lockout configuration; failed-logon alerts"],
   ["03.01.10  Device Lock","PS-9 — session lock after inactivity","GPO/MDM config; inactivity-lock test results"],
   ["03.01.11  Session Termination","PS-10 — session termination","Session-termination configuration"],
   ["03.01.12  Remote Access","PS-7, PS-8 — remote access controls; MFA","VPN/remote-access config; MFA enrollment logs"],
   ["03.01.16  Wireless Access","PS-11 — wireless controls and authorization","Wireless config; WPA3/enterprise auth records"],
   ["03.01.18  Access Control for Mobile Devices","PS-12, PS-13 — mobile policy; MDM; CUI controls","MDM enrollment reports; mobile policy acknowledgments"],
   ["03.01.20  Use of External Systems","PS-14 — external-system controls; use agreements","External-connection approvals; signed use agreements"],
 ],
}
B.build(spec)
print("Access_Control_Policy.docx rebuilt to match the set")
