# -*- coding: utf-8 -*-
import sys; sys.path.insert(0,'tools')
import policy_builder as B
P="policy_library/"
S=[]
S.append({"title":"Politique de gestion de la configuration","path":P+"Configuration_Management_Policy.fr.docx",
 "purpose":"La présente politique établit comment [Nom de l'organisation] définit des configurations de référence sécurisées pour les systèmes qui traitent, stockent ou transmettent de l'information contrôlée non classifiée (CUI), et comment les changements à ces systèmes sont contrôlés tout au long de leur cycle de vie. Les configurations non gérées et les changements non contrôlés sont une cause majeure de faiblesses. En imposant des configurations durcies, la gestion des changements, la fonctionnalité minimale et un inventaire exact des composants, cette politique réduit la surface d'attaque et maintient les systèmes dans un état connu et sécurisé.",
 "scope":["Tous les systèmes, postes, serveurs, équipements réseau et services infonuagiques qui traitent, stockent ou transmettent des CUI.","Tous les changements aux configurations, logiciels et micrologiciels des systèmes visés.","Tout le personnel qui configure, modifie ou maintient les systèmes visés."],
 "definitions":[("Configuration de référence","Un ensemble documenté et approuvé de paramètres servant de point de départ sécurisé d'un système."),("Paramètre de configuration","Un réglage de matériel ou de logiciel (option de sécurité, règle de mot de passe, service activé/désactivé)."),("Gestion des changements","Le processus formel de demande, revue, approbation et consignation des changements."),("Fonctionnalité minimale","Configurer les systèmes pour ne fournir que les capacités essentielles; désactiver ports, protocoles et services inutilisés."),("Liste d'autorisation","Ne permettre que les logiciels explicitement approuvés; tout le reste est refusé par défaut.")],
 "roles":[["[Gestionnaire TI / ISSO]","Être propriétaire de la politique; approuver les configurations de référence et les changements importants; assurer la tenue de l'inventaire."],["[Administrateur système]","Appliquer et maintenir les configurations de référence; mettre en œuvre les changements approuvés; désactiver les fonctions inutiles; tenir l'inventaire à jour."],["[Approbateur de changements / CAB]","Réviser et approuver les demandes de changement; évaluer l'impact de sécurité avant déploiement."],["Tous les utilisateurs","Ne pas effectuer de changements non autorisés ni installer de logiciels non approuvés; signaler les problèmes."],["[Haute direction / RSSI]","Approuver la politique; fournir les outils; accepter le risque résiduel pour les exceptions documentées."]],
 "statements":[
   ("PS-1  Configurations de référence sécurisées","[Nom de l'organisation] doit établir, documenter et maintenir des configurations de référence sécurisées pour chaque catégorie de système, fondées sur des guides de durcissement reconnus (p. ex. balises CIS ou bases de sécurité du fournisseur). Elles doivent s'appliquer aux systèmes neufs et existants."),
   ("PS-2  Paramètres de configuration","Des paramètres de sécurité obligatoires doivent être définis par type de système et appliqués de façon centralisée (p. ex. GPO/GAM). Les écarts par rapport aux paramètres approuvés doivent être détectés et corrigés."),
   ("PS-3  Gestion des changements","Les changements aux configurations de référence doivent être demandés, soumis à une revue de sécurité, approuvés, testés lorsque possible et consignés avant déploiement. Les changements d'urgence suivent un processus accéléré et sont documentés après coup."),
   ("PS-4  Analyse d'impact de sécurité","L'impact de sécurité des changements proposés doit être analysé avant approbation afin qu'ils n'affaiblissent pas la posture ni n'introduisent de nouveau risque."),
   ("PS-5  Restrictions d'accès pour les changements","La capacité d'effectuer des changements de configuration doit être restreinte aux administrateurs autorisés, journalisée et révisée. Les changements en production ne doivent pas se faire à partir de comptes standard."),
   ("PS-6  Fonctionnalité minimale","Les systèmes doivent ne fournir que les fonctions essentielles. Les ports, protocoles, services et logiciels inutilisés doivent être désactivés ou retirés, et la fonctionnalité approuvée par rôle documentée."),
   ("PS-7  Logiciels autorisés (liste d'autorisation)","Lorsque possible, l'exécution de logiciels doit être en refus par défaut, seules les applications approuvées étant permises, en priorisant les CUI et les systèmes à grande valeur. Une liste de logiciels approuvés doit être tenue."),
   ("PS-8  Inventaire des composants","Un inventaire exact et à jour des composants (matériel, logiciels, micrologiciels) doit être tenu, indiquant où les CUI sont stockés ou traités, pour soutenir l'application de correctifs, la gestion des changements et la réponse aux incidents."),
   ("PS-9  Surveillance de la configuration et dérive","Les systèmes doivent être surveillés pour les changements non autorisés et la dérive par rapport à la référence approuvée; les écarts doivent être investigués et corrigés."),
 ],
 "procedures":[
   ("6.1  Référence et durcissement",["Définir les configurations de référence (CIS/fournisseur); déployer par GPO/GAM.","Analyser ou auditer la conformité selon un calendrier.","Corriger la dérive dans un délai fondé sur le risque."],"Documents de référence; exportations GPO/GAM; rapports de conformité; registres de correction."),
   ("6.2  Gestion des changements",["Soumettre les demandes avec impact de sécurité; obtenir l'approbation; tester et déployer.","Consigner ce qui a changé, quand, par qui et l'approbation."],"Demandes/approbations de changement (PV du CAB ou billets); journal des changements; plans de retour arrière."),
   ("6.3  Inventaire et fonctionnalité minimale",["Tenir l'inventaire et le mettre à jour lors d'ajout/déplacement/changement.","Désactiver les services/ports inutiles; tenir la liste de logiciels approuvés et la liste d'autorisation lorsque possible."],"Inventaire des composants (daté); liste de logiciels approuvés; configuration de la liste d'autorisation; preuves de durcissement des ports/services."),
 ],
 "compliance_focus":"en vérifiant que les configurations de référence sont appliquées, que les changements suivent la gestion des changements, que l'inventaire est à jour et que la fonctionnalité inutile est désactivée.",
 "related":["Plan de sécurité du système (SSP) — inventaire et mise en œuvre des contrôles.","Politique de contrôle d'accès — restriction de qui peut effectuer des changements.","Politique d'intégrité des systèmes et de l'information — correction des failles et surveillance fondées sur des configurations exactes.","Politique d'évaluation des risques — analyse d'impact éclairant les décisions de changement."],
 "mapping_intro":"Les identifiants proviennent du NIST SP 800-171 Rev 3 (famille 03.04); ils s'appliquent également au CMMC 2.0 niveau 2 et à l'ITSP.10.171 (CPCSC).",
 "mapping":[
   ["03.04.01  Configuration de référence","PS-1 — configurations de référence sécurisées","Documents de référence; preuves de déploiement"],
   ["03.04.02  Paramètres de configuration","PS-2 — paramètres appliqués","Exportations GPO/GAM; analyses de conformité"],
   ["03.04.03  Contrôle des changements de configuration","PS-3 — gestion des changements","Demandes/approbations; journal des changements"],
   ["03.04.04  Analyses d'impact","PS-4 — analyse d'impact de sécurité","Analyses d'impact dans les billets de changement"],
   ["03.04.05  Restrictions d'accès pour les changements","PS-5 — accès aux changements restreint et journalisé","Contrôles d'accès administrateur; journaux de changements"],
   ["03.04.06  Fonctionnalité minimale","PS-6 — désactiver les fonctions inutiles","Preuves de durcissement; liste des fonctions approuvées"],
   ["03.04.08  Logiciels autorisés – permis par exception","PS-7 — liste d'autorisation","Liste de logiciels approuvés; configuration"],
   ["03.04.10  Inventaire des composants","PS-8 — inventaire des composants","Inventaire des composants (daté)"],
   ["03.04.11  Emplacement de l'information","PS-8 — où résident les CUI","Inventaire indiquant les emplacements des CUI"],
   ["03.04.12  Configuration pour zones à risque élevé","PS-1, PS-6 — config durcie pour déplacements/zones à risque","Configurations durcies d'appareils à risque élevé"],
 ]})

S.append({"title":"Politique d'identification et d'authentification","path":P+"Identification_Authentication_Policy.fr.docx",
 "purpose":"La présente politique établit comment [Nom de l'organisation] identifie de façon unique les utilisateurs et les appareils et vérifie leur identité avant d'accorder l'accès aux systèmes qui traitent, stockent ou transmettent de l'information contrôlée non classifiée (CUI). Une identification et une authentification fortes — surtout l'authentification multifacteur — comptent parmi les défenses les plus efficaces contre la compromission de comptes. Cette politique garantit que chaque action est attribuable à une personne et que les identifiants sont gérés de façon sécurisée tout au long de leur cycle de vie.",
 "scope":["Tous les utilisateurs (employés, sous-traitants, fournisseurs) et tous les appareils qui accèdent aux systèmes visés.","Tous les mécanismes d'authentification : mots de passe, AMF, certificats et identifiants de comptes de service.","Tous les systèmes qui traitent, stockent ou transmettent des CUI."],
 "definitions":[("Identifiant","Un nom unique (p. ex. nom d'utilisateur) distinguant un utilisateur, un appareil ou un processus."),("Authentifiant","Élément servant à prouver l'identité (mot de passe, jeton matériel, clé d'accès/FIDO2, certificat)."),("Authentification multifacteur (AMF)","Exiger deux facteurs indépendants ou plus (savoir, avoir, être)."),("AMF résistante à l'hameçonnage","AMF difficile à contourner par hameçonnage (p. ex. FIDO2/clés d'accès, ICP)."),("Compte de service","Un compte non humain utilisé par une application ou un processus.")],
 "roles":[["[Gestionnaire TI / ISSO]","Être propriétaire de la politique; définir les normes d'authentification; imposer l'AMF; superviser la gestion des identifiants."],["[Administrateur système]","Attribuer des identifiants uniques; configurer et imposer l'AMF et les règles de mots de passe; gérer les authentifiants et comptes de service."],["[Ressources humaines]","Fournir l'information d'identité autoritative pour l'approvisionnement et le retrait."],["Tous les utilisateurs","Protéger leurs identifiants; utiliser l'AMF; ne jamais partager de comptes; signaler les compromissions."],["[Haute direction / RSSI]","Approuver la politique; financer les outils; accepter le risque résiduel."]],
 "statements":[
   ("PS-1  Identification unique","Chaque utilisateur, appareil et processus accédant aux systèmes visés doit être identifié de façon unique. Les comptes partagés ou génériques sont interdits sur les systèmes contenant des CUI, sauf s'ils sont techniquement inévitables, approuvés et documentés avec des contrôles compensatoires."),
   ("PS-2  Identification et authentification des appareils","Les appareils qui se connectent aux réseaux ou systèmes visés doivent être identifiés et authentifiés lorsque possible (p. ex. 802.1X, certificats ou vérification de conformité)."),
   ("PS-3  Authentification multifacteur","L'AMF doit être exigée pour tous les utilisateurs, en priorisant les facteurs résistants à l'hameçonnage (FIDO2/clés d'accès, ICP) plutôt que le SMS, en commençant par les comptes privilégiés, l'accès à distance et l'accès aux CUI."),
   ("PS-4  Authentification résistante à la réinsertion","L'authentification des comptes privilégiés et de l'accès réseau doit utiliser des mécanismes résistants aux attaques par réinsertion (replay)."),
   ("PS-5  Gestion des identifiants","Les identifiants doivent être émis par un processus autorisé, jamais réutilisés et désactivés après une période d'inactivité définie. La correspondance identifiant-personne doit être tenue."),
   ("PS-6  Gestion des mots de passe","Lorsque des mots de passe sont utilisés, ils doivent suivre les pratiques actuelles : phrases de passe fondées sur la longueur, vérification contre les mots de passe compromis, pas de rotation périodique forcée sans indication de compromission, et stockage sécurisé (hachage salé). Les mots de passe par défaut doivent être changés avant le déploiement."),
   ("PS-7  Gestion des authentifiants","Les authentifiants (jetons, certificats, clés) doivent être émis, protégés, renouvelés, révoqués et récupérés par des processus contrôlés. Les authentifiants perdus ou compromis doivent être révoqués rapidement."),
   ("PS-8  Rétroaction d'authentification","La rétroaction d'authentification (p. ex. masquage de la saisie du mot de passe) doit être gérée pour ne pas exposer les identifiants à l'observation."),
   ("PS-9  Identifiants de service et privilégiés","Les identifiants de comptes de service et privilégiés doivent être placés en coffre-fort, renouvelés et contrôlés; les accès privilégiés permanents doivent être minimisés."),
 ],
 "procedures":[
   ("6.1  Approvisionnement et AMF",["Attribuer des identifiants uniques par le processus autorisé; inscrire les utilisateurs à l'AMF avant l'accès.","Imposer l'AMF résistante à l'hameçonnage pour l'accès administrateur, à distance et aux CUI."],"Configuration du fournisseur d'identité; rapports d'inscription à l'AMF; demandes d'accès."),
   ("6.2  Cycle de vie des identifiants",["Appliquer les règles de mots de passe/phrases avec vérification des mots de passe compromis.","Mettre en coffre-fort et renouveler les identifiants de service/privilégiés; révoquer en cas de perte ou de départ."],"Configuration de la politique de mots de passe; journaux du coffre-fort; registres de révocation."),
   ("6.3  Hygiène des identifiants",["Désactiver les identifiants après l'inactivité définie; empêcher la réutilisation.","Tenir la correspondance identifiant-personne."],"Rapports de désactivation pour inactivité; inventaire des identifiants."),
 ],
 "compliance_focus":"en vérifiant l'identification unique, l'application de l'AMF (surtout résistante à l'hameçonnage pour l'accès privilégié/à distance/aux CUI) et la gestion sécurisée du cycle de vie des identifiants.",
 "related":["Politique de contrôle d'accès — autorisation qui suit l'authentification.","Politique de sécurité du personnel — entrée/départ déclenchant l'approvisionnement.","Plan de sécurité du système (SSP) — détails de mise en œuvre de l'authentification.","Politique de gestion de la configuration — paramètres de référence imposant les règles d'authentification."],
 "mapping_intro":"Les identifiants proviennent du NIST SP 800-171 Rev 3 (famille 03.05); ils s'appliquent également au CMMC 2.0 niveau 2 et à l'ITSP.10.171 (CPCSC).",
 "mapping":[
   ["03.05.01  Identification et authentification des utilisateurs","PS-1, PS-3 — identifiants uniques; AMF","Config du fournisseur d'identité; rapports d'AMF"],
   ["03.05.02  Identification et authentification des appareils","PS-2 — authentification des appareils","Config 802.1X/certificat/conformité"],
   ["03.05.03  Authentification multifacteur","PS-3 — AMF partout, résistante à l'hameçonnage","Preuves d'inscription et d'application de l'AMF"],
   ["03.05.04  Authentification résistante à la réinsertion","PS-4 — résistance à la réinsertion","Configuration du mécanisme d'authentification"],
   ["03.05.05  Gestion des identifiants","PS-5 — émission, non-réutilisation, désactivation","Inventaire des identifiants; rapports de désactivation"],
   ["03.05.07  Gestion des mots de passe","PS-6 — règles modernes; pas de valeurs par défaut","Config de la politique; vérification des mots de passe compromis"],
   ["03.05.11  Rétroaction d'authentification","PS-8 — rétroaction masquée","Configuration de l'interface d'ouverture de session"],
   ["03.05.12  Gestion des authentifiants","PS-7, PS-9 — cycle de vie; coffre-fort","Émission/révocation des authentifiants; journaux du coffre-fort"],
 ]})

S.append({"title":"Politique et plan de réponse aux incidents","path":P+"Incident_Response_Policy_Plan.fr.docx",
 "purpose":"La présente politique et ce plan établissent comment [Nom de l'organisation] se prépare aux incidents de cybersécurité, les détecte, les analyse, les contient, les éradique, s'en rétablit et les signale, pour les systèmes qui traitent, stockent ou transmettent de l'information contrôlée non classifiée (CUI). Une réponse préparée et exercée limite les dommages, préserve les preuves et respecte les obligations contractuelles et réglementaires de signalement. Ce document définit les rôles, les niveaux de gravité et les étapes que suivent les intervenants.",
 "scope":["Tous les incidents et incidents soupçonnés de cybersécurité touchant les systèmes, données ou CUI visés.","Tout le personnel, sous-traitants et tiers impliqués dans la détection, le signalement ou la réponse.","Tous les systèmes qui traitent, stockent ou transmettent des CUI."],
 "definitions":[("Événement","Toute occurrence observable dans un système ou un réseau."),("Incident","Un événement qui compromet réellement ou de façon imminente la confidentialité, l'intégrité ou la disponibilité."),("Confinement","Actions visant à limiter la portée et l'impact d'un incident."),("Éradication","Suppression de la cause de l'incident (p. ex. maliciel, accès non autorisé)."),("Incident touchant des CUI","Incident impliquant la compromission soupçonnée ou confirmée de CUI, avec obligations de signalement précises.")],
 "roles":[["[Gestionnaire TI / ISSO]","Être propriétaire de la politique; diriger ou désigner le responsable de la réponse; maintenir et tester le plan."],["Responsable de la réponse aux incidents","Coordonner les activités; déclarer la gravité; gérer les communications et le signalement."],["[Administrateur système] / Intervenants","Exécuter le confinement, l'éradication et le rétablissement; préserver les preuves."],["[Haute direction / RSSI]","Approuver les décisions majeures; autoriser les notifications externes; accepter le risque résiduel."],["Tous les utilisateurs","Signaler immédiatement tout incident soupçonné par le canal défini; ne pas enquêter seuls."]],
 "statements":[
   ("PS-1  Capacité de réponse aux incidents","[Nom de l'organisation] doit maintenir une capacité de réponse couvrant la préparation, la détection et l'analyse, le confinement, l'éradication, le rétablissement et l'activité post-incident."),
   ("PS-2  Plan de réponse documenté","Un plan écrit doit définir les rôles, les niveaux de gravité, l'arbre d'appels/d'escalade, l'autorité décisionnelle et les obligations de signalement. Il doit demeurer accessible durant une panne (y compris hors ligne) et être fourni au personnel concerné."),
   ("PS-3  Détection et signalement","Les utilisateurs et les systèmes doivent disposer de canaux clairs pour signaler les incidents soupçonnés. Les alertes et la surveillance (issues des contrôles d'audit et d'intégrité) doivent alimenter la détection."),
   ("PS-4  Triage et gravité","Les événements signalés doivent être triés et se voir attribuer un niveau de gravité qui détermine les délais de réponse, l'escalade et la notification."),
   ("PS-5  Confinement, éradication et rétablissement","Les intervenants doivent contenir les incidents pour en limiter l'impact, éradiquer la cause et rétablir les systèmes à un état connu et fiable, en préservant les preuves."),
   ("PS-6  Signalement et notification","Les incidents touchant des CUI doivent être signalés aux parties requises (p. ex. agents de contrats gouvernementaux / le DoD selon le contrat) dans le délai prescrit. Les notifications internes et externes doivent être coordonnées par la direction."),
   ("PS-7  Mise à l'essai du plan","Le plan doit être testé au moins [annuellement] (p. ex. exercice sur table); les lacunes doivent être consignées et réinjectées dans le plan."),
   ("PS-8  Formation à la réponse aux incidents","Les intervenants et le personnel concerné doivent recevoir une formation adaptée à leur rôle, y compris comment et quand signaler."),
   ("PS-9  Revue post-incident","Après les incidents importants, une revue des leçons apprises doit être menée et les améliorations appliquées aux contrôles et au plan."),
 ],
 "procedures":[
   ("6.1  De la détection au confinement",["Un utilisateur/système signale un événement par le canal défini; le responsable trie et attribue la gravité.","Les intervenants contiennent l'incident en préservant les journaux et les preuves."],"Billets d'incident horodatés; attributions de gravité; registres de préservation des preuves."),
   ("6.2  Éradication, rétablissement et signalement",["Supprimer la cause; rétablir les systèmes à un état connu et fiable; valider.","Pour les incidents touchant des CUI, signaler aux parties requises dans le délai prescrit."],"Registres de rétablissement; rapports d'incident CUI et confirmations de soumission."),
   ("6.3  Tester et améliorer",["Mener un exercice sur table annuel; consigner les lacunes.","Mener une revue des leçons apprises après les incidents importants; mettre à jour le plan."],"Registres d'exercice; rapports de leçons apprises; historique des révisions du plan."),
 ],
 "compliance_focus":"en vérifiant que le plan est à jour et testé, que les incidents sont triés et documentés, que les délais de signalement des CUI sont respectés et que les intervenants sont formés.",
 "related":["Plan de sécurité du système (SSP) — contexte des systèmes et des CUI.","Politique d'audit et de responsabilisation — journaux soutenant la détection et l'enquête.","Politique d'intégrité des systèmes et de l'information — surveillance et détection de maliciels alimentant la réponse.","Politique de contrôle d'accès — actions sur les comptes lors du confinement."],
 "mapping_intro":"Les identifiants proviennent du NIST SP 800-171 Rev 3 (famille 03.06); ils s'appliquent également au CMMC 2.0 niveau 2 et à l'ITSP.10.171 (CPCSC).",
 "mapping":[
   ["03.06.01  Traitement des incidents","PS-1, PS-5 — cycle de traitement","Dossiers d'incident; preuves de confinement/rétablissement"],
   ["03.06.02  Surveillance, signalement et assistance","PS-3, PS-6 — détection, signalement, assistance","Canaux de signalement; rapports d'incident CUI"],
   ["03.06.03  Mise à l'essai de la réponse","PS-7 — essais annuels","Registres d'exercice sur table"],
   ["03.06.04  Formation à la réponse","PS-8 — formation des intervenants","Relevés d'achèvement de formation"],
   ["03.06.05  Plan de réponse aux incidents","PS-2 — plan documenté","Le plan de réponse (daté, diffusé)"],
 ]})

S.append({"title":"Politique de maintenance des systèmes","path":P+"System_Maintenance_Policy.fr.docx",
 "purpose":"La présente politique établit comment [Nom de l'organisation] effectue la maintenance des systèmes qui traitent, stockent ou transmettent de l'information contrôlée non classifiée (CUI) de façon sécurisée, et comment elle contrôle les outils, les supports, le personnel et les sessions de maintenance à distance (non locales). Une maintenance non contrôlée peut introduire des maliciels ou exposer des CUI. Cette politique garantit que la maintenance est autorisée, supervisée et n'affaiblit pas la sécurité.",
 "scope":["Toute la maintenance planifiée et non planifiée des systèmes et composants visés.","Tous les outils, équipements de diagnostic et supports utilisés sur les systèmes visés.","Tout le personnel interne, les fournisseurs et les tiers qui effectuent la maintenance."],
 "definitions":[("Outil de maintenance","Matériel/logiciel servant à diagnostiquer, réparer ou entretenir un système."),("Maintenance non locale","Maintenance effectuée par un réseau depuis l'extérieur de l'emplacement du système."),("Personnel de maintenance","Personnes (internes ou externes) qui effectuent la maintenance."),("Assainissement","Retrait des données d'un équipement ou support afin qu'elles ne puissent être récupérées.")],
 "roles":[["[Gestionnaire TI / ISSO]","Être propriétaire de la politique; autoriser la maintenance et le personnel; approuver les méthodes de maintenance non locale."],["[Administrateur système]","Planifier et effectuer la maintenance; inspecter et contrôler les outils/supports; superviser la maintenance par les fournisseurs."],["Personnel de maintenance / Fournisseurs","Effectuer la maintenance autorisée selon les contrôles convenus; ne pas retirer de CUI sans autorisation."],["Tous les utilisateurs","Signaler les besoins de maintenance par le canal approprié; ne pas permettre d'entretien non autorisé."],["[Haute direction / RSSI]","Approuver la politique; accepter le risque résiduel pour les exceptions documentées."]],
 "statements":[
   ("PS-1  Maintenance autorisée","La maintenance des systèmes visés doit être autorisée, planifiée lorsque possible et consignée. Seul le personnel autorisé peut effectuer la maintenance."),
   ("PS-2  Contrôle des outils et supports de maintenance","Les outils et supports utilisés pour la maintenance doivent être inspectés et analysés à la recherche de code malveillant avant leur utilisation sur les systèmes visés, et contrôlés pour empêcher tout usage non autorisé."),
   ("PS-3  Maintenance non locale (à distance)","La maintenance à distance doit être autorisée, menée par des canaux approuvés, chiffrés et protégés par l'AMF, surveillée et terminée à la fin. Les registres des sessions à distance doivent être conservés."),
   ("PS-4  Personnel de maintenance","Le personnel de maintenance doit être autorisé; le personnel non habilité ou non escorté doit être supervisé par du personnel autorisé. Les fournisseurs externes doivent opérer sous entente."),
   ("PS-5  Assainissement des supports et équipements","Les équipements ou supports quittant l'organisation pour une maintenance hors site, une élimination ou une réutilisation doivent voir leurs CUI retirés ou être assainis conformément à la Politique de protection des supports."),
   ("PS-6  Supervision et vérification","Les activités de maintenance touchant des fonctions de sécurité doivent être vérifiées par la suite pour confirmer que l'état de sécurité du système est intact."),
 ],
 "procedures":[
   ("6.1  Effectuer la maintenance",["Autoriser et planifier la maintenance; inspecter/analyser les outils et supports avant utilisation.","Consigner ce qui a été fait, par qui et quand."],"Autorisations et registres de maintenance; registres d'analyse des outils/supports."),
   ("6.2  Maintenance à distance",["Autoriser la maintenance non locale; se connecter par un canal approuvé, chiffré et protégé par l'AMF; surveiller et terminer.","Assainir les équipements/supports avant tout entretien hors site ou élimination."],"Autorisations et registres de sessions à distance; registres d'assainissement."),
 ],
 "compliance_focus":"en vérifiant que la maintenance est autorisée et consignée, que les outils/supports sont analysés, que la maintenance à distance est contrôlée et que les équipements sont assainis avant de quitter l'organisation.",
 "related":["Politique de protection des supports — assainissement des supports et équipements.","Politique de contrôle d'accès — accès à distance et AMF pour la maintenance non locale.","Politique de gestion de la configuration — vérification de la configuration après maintenance.","Plan de sécurité du système (SSP) — systèmes visés et ententes de maintenance."],
 "mapping_intro":"Les identifiants proviennent du NIST SP 800-171 Rev 3 (famille 03.07); ils s'appliquent également au CMMC 2.0 niveau 2 et à l'ITSP.10.171 (CPCSC).",
 "mapping":[
   ["03.07.04  Outils de maintenance","PS-2 — contrôler et analyser les outils/supports","Registres d'inspection et d'analyse"],
   ["03.07.05  Maintenance non locale","PS-3 — maintenance à distance contrôlée","Autorisations et registres de sessions à distance"],
   ["03.07.06  Personnel de maintenance","PS-4 — personnel autorisé/supervisé","Autorisations de maintenance; ententes avec fournisseurs"],
 ]})

for s in S: B.build_fr(s); print("  ", s["path"].split("/")[-1])
print(f"FR batch2: {len(S)}")
