# -*- coding: utf-8 -*-
import sys; sys.path.insert(0,'tools')
import policy_builder as B
P="policy_library/"
S=[]
S.append({"title":"Plan du programme de sécurité de l'information (SSP)","path":P+"Information_Security_Program_Plan_SSP.fr.docx",
 "purpose":"Le présent document établit le programme de sécurité de l'information de [Nom de l'organisation] et sert de fondement à son plan de sécurité du système (SSP). Il décrit le périmètre du système, l'environnement d'information contrôlée non classifiée (CUI), la manière dont les contrôles de sécurité sont mis en œuvre, et la façon dont le programme est planifié, doté de ressources et gouverné. Le SSP est la référence autoritative que les auditeurs utilisent pour comprendre l'environnement et vérifier la mise en œuvre des contrôles.",
 "scope":["Le périmètre défini du système qui traite, stocke ou transmet des CUI, y compris les composants, les flux de données et les connexions.","La gouvernance, les rôles et la planification du programme de sécurité qui soutiennent la mise en œuvre des contrôles.","Tout le personnel et les tiers opérant à l'intérieur du périmètre."],
 "definitions":[("Plan de sécurité du système (SSP)","Le document autoritatif décrivant le système, son périmètre et la mise en œuvre de chaque contrôle de sécurité."),("Périmètre du système","L'ensemble des composants qui constituent le système et sa portée d'autorisation."),("Règles de conduite","Les règles documentées que les utilisateurs s'engagent à suivre pour accéder au système."),("Programme de sécurité","L'ensemble organisé de politiques, rôles, ressources et activités qui protègent l'information.")],
 "roles":[["[Gestionnaire TI / ISSO]","Être propriétaire du programme et du SSP; tenir à jour le périmètre et la mise en œuvre; coordonner les évaluations."],["[Administrateur système]","Tenir l'inventaire des composants et la documentation des flux de données; mettre en œuvre les contrôles décrits."],["[Haute direction / RSSI]","Approuver le programme et le SSP; fournir les ressources; accepter le risque résiduel."],["Tous les utilisateurs","Reconnaître et suivre les règles de conduite."]],
 "statements":[
   ("PS-1  Politiques et procédures","[Nom de l'organisation] doit établir, maintenir et diffuser les politiques et procédures de sécurité requises pour protéger les CUI, et les réviser au moins [annuellement]."),
   ("PS-2  Plan de sécurité du système","Un plan de sécurité du système doit être élaboré et maintenu, décrivant le périmètre, l'environnement, les catégories de CUI, les interconnexions et la mise en œuvre de chaque contrôle requis; il doit être révisé et mis à jour selon une cadence définie et après tout changement important."),
   ("PS-3  Périmètre et inventaire","Le périmètre du système, l'inventaire des composants et les flux de données des CUI doivent être documentés et tenus à jour."),
   ("PS-4  Règles de conduite","Les règles de conduite des utilisateurs (y compris pour la manipulation des CUI) doivent être documentées, reconnues avant l'accès et reconnues de nouveau périodiquement."),
   ("PS-5  Gouvernance et dotation du programme","Les rôles de sécurité doivent être attribués et le programme suffisamment doté; le SSP doit renvoyer aux politiques de soutien (contrôle d'accès, audit, etc.)."),
   ("PS-6  Plan d'action et de jalons","Les lacunes de mise en œuvre des contrôles doivent être suivies dans un POA&M associé au SSP."),
 ],
 "procedures":[
   ("6.1  Tenir le SSP",["Documenter le périmètre, l'inventaire, les catégories de CUI, les interconnexions et la mise en œuvre des contrôles.","Réviser/mettre à jour selon la cadence et après tout changement important."],"SSP courant (daté); documentation du périmètre/inventaire/flux de données."),
   ("6.2  Gouvernance",["Maintenir et diffuser les politiques; attribuer les rôles de sécurité.","Obtenir les reconnaissances des règles de conduite; suivre les lacunes dans le POA&M."],"Ensemble de politiques (daté); attributions de rôles; règles de conduite signées; POA&M."),
 ],
 "compliance_focus":"en vérifiant que le SSP est à jour et complet, que les politiques sont maintenues et diffusées, que les règles de conduite sont reconnues et que les lacunes sont suivies dans le POA&M.",
 "related":["Toutes les politiques de cet ensemble — référencées par le SSP pour la mise en œuvre des contrôles.","Politique d'évaluation de la sécurité et de surveillance continue — évaluation et POA&M.","Politique d'évaluation des risques — entrées de risque du programme.","Politique de gestion de la configuration — inventaire des composants et périmètre."],
 "mapping_intro":"Les identifiants proviennent du NIST SP 800-171 Rev 3 (famille 03.15 — Planification); ils s'appliquent également au CMMC 2.0 niveau 2 et à l'ITSP.10.171 (CPCSC).",
 "mapping":[
   ["03.15.01  Politiques et procédures","PS-1, PS-5 — politiques maintenues et diffusées","Ensemble de politiques (daté); preuve de diffusion"],
   ["03.15.02  Plan de sécurité du système","PS-2, PS-3, PS-6 — SSP, périmètre, POA&M","SSP courant; périmètre/inventaire; POA&M"],
   ["03.15.03  Règles de conduite","PS-4 — règles documentées et reconnues","Règles de conduite signées"],
 ]})

S.append({"title":"Politique d'acquisition des systèmes et des services","path":P+"System_Services_Acquisition_Policy.fr.docx",
 "purpose":"La présente politique établit comment [Nom de l'organisation] intègre la sécurité à l'acquisition et au développement des systèmes, composants et services qui traiteront, stockeront ou transmettront de l'information contrôlée non classifiée (CUI). Les exigences de sécurité définies avant l'acquisition sont bien moins coûteuses et plus efficaces que les correctifs après coup. Cette politique garantit que les principes d'ingénierie de sécurité sont appliqués, que les composants non pris en charge sont évités et que les fournisseurs de services externes respectent les exigences relatives aux CUI.",
 "scope":["L'acquisition et le développement de systèmes, composants, logiciels et services qui traiteront des CUI.","Les services de systèmes externes et les fournisseurs opérant pour le compte de l'organisation.","La mise hors service des composants non pris en charge."],
 "definitions":[("Principes d'ingénierie de sécurité","Pratiques de conception (p. ex. moindre privilège, défense en profondeur, valeurs par défaut sécurisées) appliquées à la construction des systèmes."),("Composant non pris en charge","Matériel/logiciel ne recevant plus de mises à jour de sécurité de son fournisseur."),("Service de système externe","Un service fourni par un fournisseur externe (p. ex. SaaS ou service géré) utilisé par l'organisation.")],
 "roles":[["[Gestionnaire TI / ISSO]","Être propriétaire de la politique; définir les exigences de sécurité des acquisitions; approuver les services externes; suivre l'état de prise en charge des composants."],["[Administrateur système] / Développeurs","Appliquer les principes d'ingénierie de sécurité; configurer les composants de façon sécurisée; remplacer les composants non pris en charge."],["[Approvisionnement]","Inclure les exigences de sécurité dans les contrats; obtenir les attestations des fournisseurs."],["[Haute direction / RSSI]","Approuver la politique; accepter le risque résiduel pour les exceptions documentées."]],
 "statements":[
   ("PS-1  Exigences de sécurité à l'acquisition","Les exigences de sécurité (y compris les exigences de protection des CUI telles que les contrôles applicables du NIST 800-171 / CMMC) doivent être définies et incluses dans les acquisitions et contrats portant sur des systèmes, composants et services qui traiteront des CUI."),
   ("PS-2  Principes d'ingénierie de sécurité","Les principes d'ingénierie de sécurité (p. ex. moindre privilège, défense en profondeur, valeurs par défaut sécurisées, minimisation) doivent être appliqués lors de la conception, du développement et de la configuration des systèmes."),
   ("PS-3  Composants non pris en charge","Les composants non pris en charge doivent être cernés et remplacés; lorsque leur usage continu est inévitable, des contrôles compensatoires documentés et un plan de correction doivent être en place."),
   ("PS-4  Services de systèmes externes","Les fournisseurs de services externes qui stockent, traitent ou transmettent des CUI doivent satisfaire à des exigences de sécurité équivalentes; les responsabilités doivent être définies dans des ententes, et la conformité des fournisseurs vérifiée (p. ex. attestations, certifications)."),
   ("PS-5  Acceptation et vérification","Avant la mise en service des systèmes ou services, leur configuration de sécurité et leurs contrôles doivent être vérifiés par rapport aux exigences définies."),
 ],
 "procedures":[
   ("6.1  Acquérir de façon sécurisée",["Définir et inclure les exigences de sécurité/CUI dans les acquisitions et contrats.","Appliquer les principes d'ingénierie de sécurité à la conception et à la configuration; vérifier avant la mise en service."],"Exigences de sécurité d'acquisition/de contrat; preuves de conception/configuration; listes de vérification d'acceptation."),
   ("6.2  Fournisseurs et cycle de vie",["Évaluer et contracter les fournisseurs externes traitant des CUI; vérifier la conformité.","Cerner et remplacer les composants non pris en charge; documenter les contrôles compensatoires au besoin."],"Ententes et attestations de fournisseurs; inventaire des composants non pris en charge et plans de correction."),
 ],
 "compliance_focus":"en vérifiant que les exigences de sécurité sont incluses dans les acquisitions, que les principes d'ingénierie de sécurité sont appliqués, que les composants non pris en charge sont gérés et que les fournisseurs de services CUI externes respectent les exigences.",
 "related":["Politique de gestion des risques liés à la chaîne d'approvisionnement — risque des fournisseurs et de la chaîne.","Politique de gestion de la configuration — configuration sécurisée des composants acquis.","Politique d'évaluation des risques — évaluation du risque d'acquisition et des fournisseurs.","Plan de sécurité du système (SSP) — périmètre incluant les services externes."],
 "mapping_intro":"Les identifiants proviennent du NIST SP 800-171 Rev 3 (famille 03.16); ils s'appliquent également au CMMC 2.0 niveau 2 et à l'ITSP.10.171 (CPCSC).",
 "mapping":[
   ["03.16.01  Principes d'ingénierie de sécurité","PS-2, PS-5 — principes d'ingénierie; vérification","Preuves de conception/config; listes de vérification d'acceptation"],
   ["03.16.02  Composants non pris en charge","PS-3 — gérer/remplacer les composants non pris en charge","Inventaire des composants non pris en charge; plans de correction"],
   ["03.16.03  Services de systèmes externes","PS-1, PS-4 — exigences et conformité des fournisseurs","Exigences contractuelles; attestations des fournisseurs"],
 ]})

S.append({"title":"Politique de gestion des risques liés à la chaîne d'approvisionnement","path":P+"Supply_Chain_Risk_Management_Policy.fr.docx",
 "purpose":"La présente politique établit comment [Nom de l'organisation] gère le risque de cybersécurité découlant de ses fournisseurs, de ses produits et de l'ensemble de la chaîne d'approvisionnement pour les systèmes et services qui traitent de l'information contrôlée non classifiée (CUI). Des fournisseurs ou composants compromis ou non fiables peuvent miner même de solides contrôles internes. Cette politique définit la planification du risque lié à la chaîne d'approvisionnement, les exigences envers les fournisseurs et les pratiques d'acquisition.",
 "scope":["Les fournisseurs, manufacturiers et prestataires dont les produits ou services touchent les CUI ou les systèmes visés.","Les stratégies, outils et méthodes d'acquisition utilisés pour obtenir ces produits et services.","La gestion continue des relations et exigences de la chaîne d'approvisionnement."],
 "definitions":[("Chaîne d'approvisionnement","Le réseau de fournisseurs, produits et services qui contribuent aux systèmes de l'organisation."),("Risque lié à la chaîne d'approvisionnement","Le risque qu'un fournisseur, produit ou service introduise une vulnérabilité ou une compromission."),("Exigences envers les fournisseurs","Obligations de sécurité imposées aux fournisseurs (p. ex. transfert des exigences de protection des CUI)."),("Provenance","Connaissance de l'origine et de la chaîne de possession d'un produit ou composant.")],
 "roles":[["[Gestionnaire TI / ISSO]","Être propriétaire de la politique; tenir le plan de risque; fixer les exigences de sécurité des fournisseurs; évaluer le risque des fournisseurs."],["[Approvisionnement]","Appliquer les stratégies d'acquisition approuvées; transférer les exigences dans les contrats; obtenir les attestations."],["[Haute direction / RSSI]","Approuver la politique; accepter le risque résiduel de la chaîne d'approvisionnement."],["Tous les utilisateurs","N'utiliser que des fournisseurs/produits approuvés; signaler les préoccupations."]],
 "statements":[
   ("PS-1  Plan de gestion des risques de la chaîne d'approvisionnement","[Nom de l'organisation] doit élaborer et maintenir un plan de gestion du risque de cybersécurité de la chaîne d'approvisionnement, cernant les fournisseurs/composants critiques et les contrôles appliqués pour gérer leur risque."),
   ("PS-2  Stratégies, outils et méthodes d'acquisition","L'organisation doit utiliser des stratégies, outils et méthodes d'acquisition qui réduisent le risque de la chaîne d'approvisionnement (p. ex. acheter de sources de confiance, exiger des attestations de sécurité, vérifier la provenance lorsque possible)."),
   ("PS-3  Exigences envers les fournisseurs et transfert","Des exigences de sécurité et de protection des CUI doivent être définies pour les fournisseurs traitant des CUI ou fournissant des composants visés, et transférées par contrat; la conformité des fournisseurs doit être vérifiée."),
   ("PS-4  Évaluation du risque des fournisseurs","Les fournisseurs et produits touchant les CUI doivent être évalués quant au risque avant l'engagement et périodiquement par la suite, et les réponses au risque documentées."),
   ("PS-5  Surveillance continue","Les relations de la chaîne d'approvisionnement doivent être surveillées pour détecter les changements de risque (p. ex. atteintes chez un fournisseur, fin de prise en charge), avec action au besoin."),
 ],
 "procedures":[
   ("6.1  Planifier et exiger",["Tenir le plan de risque; cerner les fournisseurs/composants critiques.","Définir et transférer les exigences de sécurité/CUI des fournisseurs; obtenir les attestations."],"Plan de risque de la chaîne d'approvisionnement; exigences dans les contrats; attestations des fournisseurs."),
   ("6.2  Évaluer et surveiller",["Évaluer le risque des fournisseurs/produits avant l'engagement et périodiquement.","Surveiller les changements de risque; réagir au besoin."],"Évaluations de risque des fournisseurs; registres de surveillance; décisions de réponse au risque."),
 ],
 "compliance_focus":"en vérifiant qu'un plan de risque de la chaîne d'approvisionnement existe, que les exigences de sécurité/CUI des fournisseurs sont transférées et vérifiées, et que le risque des fournisseurs est évalué et surveillé.",
 "related":["Politique d'acquisition des systèmes et des services — acquisition sécurisée des systèmes et services.","Politique d'évaluation des risques — risque des fournisseurs et des produits.","Politique de gestion de la configuration — inventaire des composants et provenance.","Plan de sécurité du système (SSP) — services externes dans le périmètre."],
 "mapping_intro":"Les identifiants proviennent du NIST SP 800-171 Rev 3 (famille 03.17); ils s'appliquent également au CMMC 2.0 niveau 2 et à l'ITSP.10.171 (CPCSC).",
 "mapping":[
   ["03.17.01  Plan de gestion des risques de la chaîne d'approvisionnement","PS-1 — plan GRCA","Plan de risque de la chaîne d'approvisionnement (daté)"],
   ["03.17.02  Stratégies, outils et méthodes d'acquisition","PS-2 — acquisition réductrice de risque","Stratégie d'acquisition; preuves de sources de confiance"],
   ["03.17.03  Exigences et processus de la chaîne d'approvisionnement","PS-3, PS-4, PS-5 — exigences, évaluation, surveillance","Exigences/attestations des fournisseurs; évaluations; registres de surveillance"],
 ]})

S.append({"title":"Politique de sécurité de l'information","path":P+"Information_Security_Policy.fr.docx",
 "owner":"[Gestionnaire TI / ISSO]",
 "purpose":"Voici la politique générale de sécurité de l'information de [Nom de l'organisation]. Elle énonce les attentes de la direction quant à la protection de la confidentialité, de l'intégrité et de la disponibilité de l'information — y compris l'information contrôlée non classifiée (CUI) — et établit le cadre de politiques propres aux domaines, de rôles et de responsabilisation qui mettent en œuvre ces attentes. Toutes les autres politiques de sécurité tirent leur autorité du présent document.",
 "scope":["Toute l'information et tous les systèmes d'information détenus ou exploités par [Nom de l'organisation], avec une attention particulière aux CUI.","Tous les employés, sous-traitants et tiers qui accèdent à l'information ou aux systèmes de l'organisation.","Tous les lieux et environnements, y compris l'infonuagique, le sur place et le télétravail."],
 "definitions":[("Sécurité de l'information","Protéger la confidentialité, l'intégrité et la disponibilité de l'information."),("Confidentialité","Veiller à ce que l'information ne soit accessible qu'aux personnes autorisées."),("Intégrité","Veiller à ce que l'information soit exacte et non altérée de façon inappropriée."),("Disponibilité","Veiller à ce que l'information et les systèmes soient accessibles au besoin."),("CUI","Information contrôlée non classifiée nécessitant une protection en vertu d'une loi, d'un règlement ou d'un contrat.")],
 "roles":[["[Haute direction / RSSI]","Définir l'orientation de sécurité; approuver la présente politique et les politiques subordonnées; fournir les ressources; accepter le risque résiduel."],["[Gestionnaire TI / ISSO]","Être propriétaire du programme de sécurité; maintenir les politiques subordonnées; superviser la mise en œuvre et les rapports."],["[Gestionnaires de service / Superviseurs]","Veiller à la conformité de leur équipe; soutenir la mise en œuvre dans leur secteur."],["Tous les utilisateurs","Protéger l'information et les CUI; suivre toutes les politiques de sécurité; signaler les incidents et préoccupations."]],
 "statements":[
   ("PS-1  Engagement envers la sécurité de l'information","[Nom de l'organisation] s'engage à protéger la confidentialité, l'intégrité et la disponibilité de son information et de celle qui lui est confiée, et à respecter ses obligations légales, réglementaires et contractuelles, y compris la protection des CUI."),
   ("PS-2  Cadre de politiques","Un cadre de politiques propres aux domaines (contrôle d'accès, audit et responsabilisation, gestion de la configuration, identification et authentification, réponse aux incidents, maintenance, protection des supports, sécurité du personnel, protection physique, évaluation des risques, évaluation de la sécurité et surveillance continue, sensibilisation et formation, gestion des risques de la chaîne d'approvisionnement, protection des systèmes et des communications, intégrité des systèmes et de l'information, acquisition des systèmes et des services, et le SSP) met en œuvre la présente politique; chacune doit être maintenue et suivie."),
   ("PS-3  Rôles et responsabilisation","Les rôles et responsabilités de sécurité doivent être attribués, et chacun est responsable de respecter les politiques de sécurité."),
   ("PS-4  Approche fondée sur le risque","Les décisions de sécurité doivent être fondées sur le risque, en concentrant les ressources sur les plus grands risques pour l'information et les CUI."),
   ("PS-5  Conformité et amélioration continue","L'organisation doit surveiller la conformité, évaluer l'efficacité des contrôles et améliorer continuellement sa posture de sécurité."),
   ("PS-6  Révision de la politique","La présente politique et ses politiques subordonnées doivent être révisées au moins [annuellement] et mises à jour à mesure que l'entreprise, la technologie ou le paysage des menaces évolue."),
 ],
 "procedures":[
   ("6.1  Gouverner et maintenir",["Maintenir et diffuser la présente politique et l'ensemble des politiques subordonnées; attribuer les rôles de sécurité.","Réviser au moins annuellement et après tout changement important."],"Ensemble de politiques approuvé (daté); attributions de rôles; registres de révision."),
   ("6.2  Surveiller et améliorer",["Surveiller la conformité et l'efficacité des contrôles; suivre les lacunes dans le POA&M.","Appliquer les améliorations fondées sur les évaluations, incidents et changements."],"Rapports de conformité/évaluation; POA&M; historique des révisions."),
 ],
 "compliance_focus":"en vérifiant que le cadre de politiques est maintenu et diffusé, que les rôles sont attribués, que la conformité est surveillée et que les politiques sont révisées au moins annuellement.",
 "related":["Plan de sécurité du système (SSP) — référence de mise en œuvre des contrôles.","Toutes les politiques propres aux domaines — subordonnées à la présente politique.","Politique d'évaluation des risques — base de risque des décisions de sécurité.","Politique d'évaluation de la sécurité et de surveillance continue — conformité et amélioration."],
 "mapping_intro":"Cette politique générale est mise en œuvre par les politiques propres aux domaines et correspond principalement aux contrôles de planification. Les identifiants proviennent du NIST SP 800-171 Rev 3; ils s'appliquent également au CMMC 2.0 niveau 2 et à l'ITSP.10.171 (CPCSC).",
 "mapping":[
   ["03.15.01  Politiques et procédures","PS-1, PS-2, PS-6 — cadre de politiques; révision","La présente politique et l'ensemble subordonné (datés)"],
   ["03.15.02  Plan de sécurité du système","PS-2, PS-4 — cadre alimentant le SSP","Renvoi au SSP et au plan de programme"],
   ["(Toutes les familles 03.01–03.17)","PS-2 — mises en œuvre par les politiques subordonnées","La politique de domaine correspondant à chaque famille"],
 ]})

for s in S: B.build_fr(s); print("  ", s["path"].split("/")[-1])
print(f"FR batch5: {len(S)}")
echo
