# -*- coding: utf-8 -*-
"""Traductions françaises des banques d'auto-évaluation de maturité.

Miroir de app.maturity_banks.NIST_171R3, même clé (ref du contrôle) :
    ref -> (prompt_fr, [s5_fr, s4_fr, s3_fr, s2_fr, s1_fr])
Les énoncés vont de la maturité la plus élevée (Optimisé, 5) à la plus basse
(Aucun, 1), comme la version anglaise, pour s'apparier dans
app.seed_maturity_questions. Les contrôles absents d'ici gardent l'échelle
générique bilingue.
"""

NIST_171R3_FR: dict[str, tuple[str, list[str]]] = {
    # ── 03.01 Contrôle d'accès ────────────────────────────────────────
    "03.01.01": ("Quelle est la maturité de votre gestion des comptes : création, révision et désactivation des comptes système et applicatifs ?", [
        "Le cycle de vie des comptes est automatisé et géré de façon centralisée sur tous les systèmes; l'accès est basé sur les rôles, recertifié selon un calendrier, et chaque changement est journalisé et alerté.",
        "Des procédures documentées sont appliquées aux systèmes critiques avec des révisions d'accès régulières; la couverture des systèmes secondaires est incomplète.",
        "Des procédures sont suivies pour les systèmes clés, mais la création/désactivation et les révisions sont surtout manuelles et incohérentes.",
        "Les comptes sont créés et supprimés au cas par cas par système, sans processus standard ni révision périodique.",
        "Aucun processus défini de gestion des comptes; l'accès est accordé de façon informelle et rarement révoqué.",
    ]),
    "03.01.02": ("Avec quelle constance l'accès aux systèmes et aux CUI est-il appliqué selon les autorisations approuvées ?", [
        "L'application des accès est gérée centralement et pilotée par politique sur tous les systèmes, avec des règles basées sur les rôles et une vérification continue.",
        "Appliquée par des contrôles centraux pour les systèmes critiques; quelques systèmes reposent sur une configuration locale.",
        "Les règles d'accès sont appliquées aux systèmes clés mais gérées système par système.",
        "L'application est incohérente et configurée manuellement par système.",
        "Aucune application cohérente des accès; les permissions sont ouvertes ou non définies.",
    ]),
    "03.01.03": ("Dans quelle mesure contrôlez-vous le flux des CUI entre systèmes et réseaux (segmentation, règles de sortie) ?", [
        "Des contrôles de flux (segmentation, filtrage de sortie, DLP) sont appliqués et surveillés à toutes les frontières.",
        "Appliqués aux frontières clés pour les données critiques; certains chemins ne sont pas surveillés.",
        "Une segmentation de base et des règles de sortie existent pour les systèmes importants.",
        "Contrôle minimal et ponctuel du flux d'information.",
        "Aucun contrôle de la circulation de l'information entre les systèmes.",
    ]),
    "03.01.04": ("Dans quelle mesure les tâches sont-elles séparées pour qu'aucune personne seule ne puisse détourner des fonctions critiques ?", [
        "La séparation des tâches est définie, appliquée par des outils et révisée régulièrement sur tous les processus critiques.",
        "Appliquée aux fonctions critiques; quelques conflits subsistent dans les processus secondaires.",
        "Définie pour les fonctions clés mais appliquée manuellement.",
        "Conscience informelle de la séparation des tâches, avec peu d'application.",
        "Aucune séparation des tâches.",
    ]),
    "03.01.05": ("Dans quelle mesure limitez-vous l'accès des utilisateurs et des systèmes au strict nécessaire (moindre privilège) ?", [
        "Le moindre privilège est appliqué partout, avec recertification périodique et accès juste-à-temps.",
        "Appliqué aux systèmes critiques avec des révisions périodiques.",
        "Appliqué aux systèmes clés mais les révisions sont rares.",
        "Les accès larges sont fréquents; le moindre privilège reste un objectif.",
        "Les utilisateurs ont généralement bien plus d'accès que nécessaire.",
    ]),
    "03.01.06": ("Dans quelle mesure les comptes privilégiés (administrateur) sont-ils restreints et contrôlés ?", [
        "L'accès privilégié est minimisé, géré en juste-à-temps, protégé par MFA, et entièrement journalisé et révisé.",
        "Les comptes admin sont limités et protégés par MFA pour les systèmes critiques, avec journalisation.",
        "Les comptes admin sont identifiés et quelque peu limités, mais partagés ou largement utilisés par endroits.",
        "L'accès privilégié est peu contrôlé.",
        "Les droits admin sont largement ou définitivement attribués.",
    ]),
    "03.01.07": ("Dans quelle mesure l'usage des fonctions privilégiées est-il restreint et journalisé ?", [
        "Les fonctions privilégiées sont réservées aux rôles autorisés et chaque usage est journalisé et alerté.",
        "Restreintes et journalisées pour les systèmes critiques.",
        "Restreintes pour les systèmes clés; la journalisation est partielle.",
        "Restriction ou journalisation limitée des actions privilégiées.",
        "Les fonctions privilégiées ne sont ni restreintes ni journalisées.",
    ]),
    "03.01.08": ("Comment gérez-vous les tentatives de connexion infructueuses répétées ?", [
        "Le verrouillage/limitation est appliqué et surveillé sur tous les systèmes, avec alerte sur les schémas d'attaque.",
        "Appliqué aux systèmes critiques et à l'identité centrale.",
        "Configuré sur les systèmes clés.",
        "Incohérent ou laissé aux valeurs par défaut.",
        "Aucune limite sur les tentatives de connexion échouées.",
    ]),
    "03.01.09": ("Les systèmes affichent-ils un avis d'utilisation/consentement approuvé avant d'accorder l'accès ?", [
        "Des bannières approuvées sont appliquées sur tous les chemins d'accès et tenues à jour avec la politique.",
        "Affichées sur les systèmes critiques et d'accès distant.",
        "Présentes sur certains systèmes.",
        "Rarement utilisées.",
        "Aucun avis d'utilisation du système.",
    ]),
    "03.01.10": ("Comment les sessions sont-elles verrouillées après une période d'inactivité (verrouillage de l'appareil) ?", [
        "Le verrouillage automatique de session/appareil est appliqué partout avec des délais appropriés.",
        "Appliqué aux systèmes critiques et à la plupart des postes.",
        "Configuré sur les systèmes clés.",
        "Incohérent; repose sur les utilisateurs.",
        "Aucun verrouillage de session.",
    ]),
    "03.01.11": ("Les sessions utilisateur sont-elles terminées après des conditions définies ou une inactivité ?", [
        "La fin automatique de session est appliquée de façon cohérente sur les systèmes et applications.",
        "Appliquée aux systèmes critiques et à l'accès distant.",
        "Appliquée aux systèmes clés.",
        "Incohérente.",
        "Les sessions n'expirent jamais.",
    ]),
    "03.01.12": ("Dans quelle mesure l'accès distant est-il sécurisé, autorisé et surveillé ?", [
        "Tout l'accès distant passe par des canaux durcis, protégés par MFA et entièrement surveillés, sans tunnel fractionné.",
        "Sécurisé et protégé par MFA pour le personnel et surveillé centralement, avec des lacunes mineures.",
        "Un VPN/accès distant existe avec MFA sur les chemins clés mais une surveillance limitée.",
        "L'accès distant est permis avec des contrôles seulement basiques.",
        "L'accès distant est non contrôlé ou non surveillé.",
    ]),
    "03.01.16": ("Dans quelle mesure l'accès sans fil est-il sécurisé et autorisé ?", [
        "Le sans-fil est segmenté, fortement authentifié (p. ex. 802.1X) et surveillé en continu, avec détection des points d'accès pirates.",
        "Le sans-fil d'entreprise est chiffré et authentifié, avec surveillance en place.",
        "Le sans-fil est sécurisé avec WPA2/3 et mots de passe, avec une surveillance limitée.",
        "Sécurité sans-fil de base; les réseaux invité et corporatif ne sont pas séparés.",
        "Sans-fil ouvert ou faiblement sécurisé.",
    ]),
    "03.01.18": ("Dans quelle mesure les appareils mobiles sont-ils gérés et contrôlés ?", [
        "Tous les appareils mobiles sont inscrits au MDM, chiffrés, soumis aux politiques et effaçables à distance.",
        "Gérés et chiffrés pour les appareils de l'entreprise; le BYOD est partiellement couvert.",
        "Contrôles mobiles de base sur les appareils clés.",
        "Contrôle minimal des appareils mobiles.",
        "Aucun contrôle des appareils mobiles.",
    ]),
    "03.01.20": ("Dans quelle mesure encadrez-vous l'usage des systèmes et services externes pour les CUI ?", [
        "L'usage des systèmes/services externes est encadré par politique, approuvé et techniquement restreint, avec des solutions de rechange autorisées.",
        "Encadré pour les données critiques; un peu de shadow IT subsiste.",
        "Une politique existe mais l'application est limitée.",
        "Peu d'encadrement des systèmes externes.",
        "Aucun contrôle de l'usage des systèmes externes.",
    ]),
    "03.01.22": ("Comment garantissez-vous que les CUI ne sont jamais publiés sur des systèmes accessibles au public ?", [
        "Le contenu est révisé et approuvé avant publication, avec des analyses périodiques de divulgation accidentelle.",
        "Un processus de révision est en place pour le contenu public.",
        "Révision informelle avant publication.",
        "Peu de révision du contenu public.",
        "Aucun contrôle du contenu publié publiquement.",
    ]),
    # ── 03.02 Sensibilisation et formation ────────────────────────────
    "03.02.01": ("Quelle est la maturité de votre programme de sensibilisation à la sécurité ?", [
        "La sensibilisation est continue et mesurée (p. ex. simulations d'hameçonnage), renouvelée et suivie pour tout le personnel.",
        "Formation annuelle pour tout le personnel plus des rappels périodiques, avec suivi des complétions.",
        "Une formation annuelle existe mais le suivi et le renouvellement sont incohérents.",
        "Activité de sensibilisation occasionnelle et ponctuelle.",
        "Aucune formation de sensibilisation à la sécurité.",
    ]),
    "03.02.02": ("Quelle est la maturité de la formation par rôle pour le personnel ayant des responsabilités de sécurité ?", [
        "La formation par rôle est définie, dispensée et suivie pour chaque rôle pertinent en sécurité et renouvelée régulièrement.",
        "Dispensée pour les rôles clés, avec suivi en place.",
        "Quelques formations par rôle, dispensées de façon incohérente.",
        "Formation spécifique au rôle rare.",
        "Aucune formation par rôle.",
    ]),
    # ── 03.03 Audit et responsabilisation ─────────────────────────────
    "03.03.01": ("Quelle est la maturité de votre journalisation des événements de sécurité : quoi journaliser, où l'envoyer et combien de temps le conserver ?", [
        "La journalisation est centralisée (SIEM), couvre tous les systèmes visés et les types d'événements définis, avec rétention imposée, protection de l'intégrité et synchronisation horaire.",
        "Les systèmes critiques journalisent les événements requis vers un dépôt central avec rétention définie; certains systèmes ou types d'événements de moindre priorité ne sont pas encore couverts.",
        "Les systèmes clés génèrent et conservent des journaux, mais la collecte est en partie locale/manuelle et l'ensemble d'événements n'est pas normalisé.",
        "La journalisation est active par endroits mais ponctuelle et incohérente, et n'est pas collectée ni révisée centralement.",
        "Peu ou pas de journalisation des événements de sécurité.",
    ]),
    "03.03.02": ("Les enregistrements d'audit capturent-ils assez de détails (qui, quoi, quand, où, résultat) ?", [
        "Le contenu des journaux est normalisé pour capturer tous les champs requis sur les systèmes et est validé.",
        "Les systèmes critiques capturent le détail requis; les systèmes secondaires varient.",
        "Les systèmes clés journalisent les champs essentiels, mais le contenu n'est pas normalisé.",
        "Les journaux manquent de détails cohérents.",
        "Les journaux contiennent peu ou pas de détails utiles.",
    ]),
    "03.03.03": ("Les événements auditables sont-ils définis et générés de façon fiable sur les systèmes ?", [
        "Les événements auditables sont définis à l'échelle de l'organisation et générés et vérifiés sur tous les systèmes visés.",
        "Définis et générés pour les systèmes critiques.",
        "Générés sur les systèmes clés, mais l'ensemble d'événements n'est pas formellement défini.",
        "Génération d'audit ponctuelle.",
        "Aucune génération d'audit définie.",
    ]),
    "03.03.04": ("Que se passe-t-il en cas d'échec de la journalisation d'audit ?", [
        "Les échecs de journalisation déclenchent des alertes automatisées et une réponse définie, et sont surveillés en continu.",
        "Des alertes existent pour les systèmes critiques.",
        "Les échecs sont remarqués lors de vérifications périodiques.",
        "Les échecs sont rarement détectés.",
        "Aucune détection des échecs de journalisation.",
    ]),
    "03.03.05": ("Comment les journaux d'audit sont-ils révisés, analysés et rapportés ?", [
        "Corrélation et analyse centralisées avec rapports réguliers et alertes ajustées.",
        "Révision régulière des journaux critiques, en partie automatisée.",
        "Révision manuelle périodique des journaux clés.",
        "Journaux révisés seulement après incidents.",
        "Les journaux ne sont pas révisés.",
    ]),
    "03.03.06": ("Pouvez-vous efficacement rechercher, réduire et rapporter les données d'audit ?", [
        "L'outillage permet la recherche, la réduction et le rapport à la demande sans altérer les originaux.",
        "Disponible pour les systèmes critiques.",
        "Recherche de base sur les journaux clés.",
        "Manuel et limité.",
        "Aucune capacité de réduction ou de rapport.",
    ]),
    "03.03.07": ("Les horloges système sont-elles synchronisées et les horodatages fiables ?", [
        "Tous les systèmes se synchronisent à une source de temps faisant autorité, avec vérification.",
        "Les systèmes critiques sont synchronisés.",
        "Les systèmes clés sont synchronisés.",
        "La synchronisation horaire est incohérente.",
        "Aucune synchronisation horaire.",
    ]),
    "03.03.08": ("Comment les journaux d'audit sont-ils protégés contre l'altération ou la suppression ?", [
        "Les journaux sont en écriture unique ou centralisés, avec accès restreint et intégrité surveillée.",
        "Protégés et à accès contrôlé pour les journaux critiques.",
        "Une certaine protection sur les journaux clés.",
        "Journaux stockés localement avec une protection faible.",
        "Les journaux ne sont pas protégés.",
    ]),
    # ── 03.04 Gestion des configurations ──────────────────────────────
    "03.04.01": ("Dans quelle mesure les configurations de référence sécurisées sont-elles définies et maintenues ?", [
        "Des configurations de référence durcies sont définies, sous gestion de versions et appliquées/automatisées pour tous les types de systèmes.",
        "Des configurations de référence sont définies et appliquées aux systèmes critiques.",
        "Des configurations de référence existent pour les systèmes clés, mais la dérive n'est pas suivie.",
        "Configurations de référence informelles.",
        "Aucune configuration de référence définie.",
    ]),
    "03.04.02": ("Les paramètres de configuration sécurisés sont-ils appliqués (p. ex. référentiels CIS/STIG) ?", [
        "Les paramètres sont appliqués selon un référentiel reconnu et surveillés en continu contre la dérive.",
        "Appliqués sur les systèmes critiques.",
        "Appliqués aux systèmes clés.",
        "Un certain durcissement, appliqué de façon incohérente.",
        "Paramètres par défaut ou non gérés.",
    ]),
    "03.04.03": ("Comment les changements aux systèmes sont-ils contrôlés et approuvés ?", [
        "Tous les changements passent par un processus formel de gestion des changements avec approbation, tests et enregistrements.",
        "La gestion des changements est en place pour les systèmes critiques.",
        "Un processus de changement de base existe pour les systèmes clés.",
        "Les changements sont faits de façon informelle.",
        "Aucune gestion des changements.",
    ]),
    "03.04.04": ("Les impacts sur la sécurité sont-ils analysés avant les changements ?", [
        "Une analyse d'impact sur la sécurité est exigée et documentée pour tous les changements.",
        "Réalisée pour les changements critiques.",
        "Parfois réalisée.",
        "Rarement réalisée.",
        "Jamais réalisée.",
    ]),
    "03.04.05": ("La capacité de faire des changements est-elle restreinte et journalisée ?", [
        "L'accès aux changements est au moindre privilège, appliqué et entièrement journalisé.",
        "Restreint et journalisé sur les systèmes critiques.",
        "Restreint sur les systèmes clés.",
        "Peu contrôlé.",
        "N'importe qui peut modifier les systèmes.",
    ]),
    "03.04.06": ("Les systèmes sont-ils configurés pour n'offrir que les capacités essentielles (moindre fonctionnalité) ?", [
        "Les ports, services et fonctions inutiles sont désactivés et vérifiés en continu partout.",
        "Durcis pour les systèmes critiques.",
        "Les systèmes clés sont durcis.",
        "Un certain durcissement.",
        "Les systèmes exécutent les services par défaut.",
    ]),
    "03.04.08": ("Comment contrôlez-vous quels logiciels peuvent être installés et exécutés (liste d'autorisation) ?", [
        "Une liste d'autorisation des applications est appliquée et maintenue sur les postes et serveurs.",
        "Liste d'autorisation sur les systèmes critiques; les autres utilisent des listes de blocage.",
        "Les logiciels sont contrôlés sur les systèmes clés.",
        "Contrôle limité des logiciels.",
        "N'importe quel logiciel peut être installé ou exécuté.",
    ]),
    "03.04.10": ("Quelle est l'exhaustivité et l'actualité de votre inventaire des composants (actifs) ?", [
        "Un inventaire automatisé et réconcilié en continu couvre tous les composants et actifs CUI.",
        "Un inventaire maintenu des actifs critiques est mis à jour régulièrement.",
        "Un inventaire existe mais est mis à jour périodiquement ou manuellement.",
        "Inventaire partiel ou désuet.",
        "Aucun inventaire.",
    ]),
    "03.04.11": ("Savez-vous où les CUI sont stockés, traités et transmis ?", [
        "Les emplacements des CUI sont cartographiés, suivis et vérifiés en continu.",
        "Connus pour les dépôts critiques.",
        "Généralement connus pour les systèmes clés.",
        "Partiellement connus.",
        "L'emplacement des CUI est inconnu.",
    ]),
    "03.04.12": ("Les appareils sont-ils configurés pour les situations à risque élevé (p. ex. déplacements) ?", [
        "Des configurations durcies pour situations à risque/déplacement sont définies et appliquées, avec vérifications au retour.",
        "Appliquées aux cas à risque élevé connus.",
        "Des consignes existent.",
        "Gérées au cas par cas.",
        "Aucune configuration spéciale pour les situations à risque élevé.",
    ]),
    # ── 03.05 Identification et authentification ──────────────────────
    "03.05.01": ("Avec quelle robustesse les utilisateurs sont-ils identifiés et authentifiés de façon unique ?", [
        "Des identifiants uniques et une authentification forte résistante à l'hameçonnage sont imposés à tous les utilisateurs et systèmes, de façon centralisée.",
        "Identifiants uniques et authentification forte pour les systèmes critiques.",
        "Identifiants uniques, mais la force d'authentification varie.",
        "Des comptes partagés existent.",
        "Identification faible ou partagée.",
    ]),
    "03.05.02": ("Les appareils sont-ils identifiés et authentifiés avant l'accès au réseau ?", [
        "L'authentification des appareils (802.1X/certificats) est appliquée et surveillée sur tout le réseau.",
        "Appliquée sur les segments critiques.",
        "Appliquée sur les segments clés.",
        "Authentification des appareils limitée.",
        "Aucune authentification des appareils.",
    ]),
    "03.05.03": ("Quelle est la maturité de votre usage de l'authentification multifacteur (MFA) pour l'accès aux systèmes et aux comptes ?", [
        "Une MFA résistante à l'hameçonnage est imposée à tous les utilisateurs et sur chaque chemin d'accès (distant, privilégié, local et applications), sans exception non gérée.",
        "La MFA est imposée pour l'accès distant et privilégié et la plupart des applications; quelques systèmes hérités ou exceptions subsistent.",
        "La MFA est activée pour les systèmes clés (p. ex. VPN, courriel) mais la couverture est partielle et pas toujours imposée.",
        "La MFA est disponible mais facultative, ou utilisée seulement par certains utilisateurs ou systèmes.",
        "Aucune authentification multifacteur; l'accès repose sur les seuls mots de passe.",
    ]),
    "03.05.04": ("L'authentification résiste-t-elle aux attaques par rejeu ?", [
        "Des mécanismes résistants au rejeu sont imposés pour tout accès privilégié et réseau.",
        "Imposés pour l'accès critique et distant.",
        "Imposés pour les systèmes clés.",
        "Limité.",
        "Aucune résistance au rejeu.",
    ]),
    "03.05.05": ("Comment les identifiants sont-ils émis, gérés et retirés ?", [
        "Le cycle de vie des identifiants est géré formellement et la réutilisation est empêchée entre systèmes.",
        "Géré pour les systèmes critiques.",
        "Géré pour les systèmes clés.",
        "Informel.",
        "Identifiants non gérés.",
    ]),
    "03.05.07": ("Quelle est la robustesse de votre gestion des mots de passe et des justificatifs ?", [
        "La politique impose des mots de passe forts et vérifiés, un stockage sécurisé et une rotation seulement en cas de compromission, alignée sur les recommandations actuelles.",
        "Une politique forte est appliquée sur les systèmes critiques.",
        "Une politique de base est appliquée aux systèmes clés.",
        "Politique de mots de passe faible ou incohérente.",
        "Aucune politique de mots de passe.",
    ]),
    "03.05.11": ("La rétroaction d'authentification est-elle masquée (p. ex. mots de passe masqués) ?", [
        "La rétroaction est masquée sur tous les systèmes par défaut.",
        "Masquée sur les systèmes critiques.",
        "Masquée sur les systèmes clés.",
        "Incohérent.",
        "Les justificatifs peuvent être exposés à la saisie.",
    ]),
    "03.05.12": ("Comment les authentifiants (jetons, certificats, clés) sont-ils gérés ?", [
        "Gestion complète du cycle de vie avec émission, stockage, rotation et révocation sécurisés.",
        "Gérés pour les systèmes critiques.",
        "Gérés pour les systèmes clés.",
        "Informel.",
        "Authentifiants non gérés.",
    ]),
    # ── 03.06 Réponse aux incidents ───────────────────────────────────
    "03.06.01": ("Quelle est la maturité de votre capacité de traitement des incidents (préparation, détection, analyse, confinement, rétablissement) ?", [
        "Un plan de réponse aux incidents documenté est exercé régulièrement (simulations), avec rôles, outils et revues post-incident qui alimentent l'amélioration continue.",
        "Un plan et une équipe de RI formels existent et servent aux incidents réels; des tests ont lieu mais sans cadence régulière.",
        "Des procédures de base sont documentées pour les scénarios courants, mais les rôles, outils ou tests sont limités.",
        "Les incidents sont traités de façon réactive et informelle, sans plan documenté.",
        "Aucun processus de traitement des incidents; ils sont gérés au cas par cas, s'ils sont remarqués.",
    ]),
    "03.06.02": ("Comment les incidents sont-ils suivis et signalés à l'interne et à l'externe ?", [
        "Les incidents sont suivis centralement avec un signalement interne et externe (incl. régulateurs) défini et des indicateurs.",
        "Suivis et signalés pour les incidents importants.",
        "Suivi de base; le signalement est informel.",
        "Réactif, avec un suivi minimal.",
        "Aucun suivi ni signalement.",
    ]),
    "03.06.03": ("Comment la capacité de réponse aux incidents est-elle testée ?", [
        "Exercices réguliers basés sur des scénarios avec améliorations documentées.",
        "Tests périodiques.",
        "Tests occasionnels ou informels.",
        "Rarement testée.",
        "Jamais testée.",
    ]),
    "03.06.04": ("Les intervenants en cas d'incident sont-ils formés pour leurs rôles ?", [
        "Une formation par rôle en RI est dispensée et renouvelée pour tous les intervenants.",
        "Dispensée aux intervenants clés.",
        "Quelque formation.",
        "Formation rare.",
        "Aucune formation des intervenants.",
    ]),
    "03.06.05": ("Maintenez-vous un plan de réponse aux incidents à jour et diffusé ?", [
        "Le plan de RI est documenté, maintenu, diffusé et mis à jour après les incidents et changements.",
        "Un plan documenté est mis à jour périodiquement.",
        "Un plan de base existe.",
        "Un plan désuet ou partiel existe.",
        "Aucun plan de RI.",
    ]),
    # ── 03.07 Maintenance ─────────────────────────────────────────────
    "03.07.01": ("Quelle est la maturité de votre programme de maintenance des systèmes (planification, exécution et consignation) ?", [
        "La maintenance est planifiée, exécutée et documentée selon un processus contrôlé pour tous les systèmes, avec approbations et enregistrements.",
        "Maintenance contrôlée et documentée pour les systèmes critiques; certains systèmes sont gérés au cas par cas.",
        "La maintenance a lieu pour les systèmes clés, mais la planification et les enregistrements sont incohérents.",
        "La maintenance est réactive et rarement documentée.",
        "Aucun processus de maintenance géré.",
    ]),
    "03.07.04": ("Les outils de maintenance sont-ils contrôlés et inspectés ?", [
        "Les outils sont approuvés, inspectés et contrôlés, et les supports sont analysés avant usage.",
        "Contrôlés pour les systèmes critiques.",
        "Contrôle de base des outils de maintenance.",
        "Contrôle minimal.",
        "Outils de maintenance non contrôlés.",
    ]),
    "03.07.05": ("Comment la maintenance à distance (non locale) est-elle sécurisée ?", [
        "La maintenance à distance est autorisée, protégée par MFA, journalisée et terminée après usage.",
        "Sécurisée pour les systèmes critiques.",
        "Certains contrôles en place.",
        "Peu contrôlée.",
        "Maintenance à distance non contrôlée.",
    ]),
    "03.07.06": ("Le personnel de maintenance est-il autorisé et supervisé ?", [
        "Le personnel est vérifié, autorisé et escorté/supervisé, avec accès journalisé.",
        "Contrôlé pour les systèmes critiques.",
        "Vérifications de base.",
        "Contrôle minimal.",
        "Aucun contrôle du personnel de maintenance.",
    ]),
    # ── 03.08 Protection des supports ─────────────────────────────────
    "03.08.01": ("Comment les supports contenant des CUI sont-ils stockés et protégés ?", [
        "Les supports sont inventoriés, chiffrés/sécurisés et à accès contrôlé dans tous les emplacements.",
        "Sécurisés pour les supports critiques.",
        "Protection de base pour les supports clés.",
        "Protection incohérente.",
        "Les supports ne sont pas protégés.",
    ]),
    "03.08.02": ("L'accès aux supports contenant des CUI est-il restreint ?", [
        "L'accès est réservé aux rôles autorisés et journalisé.",
        "Restreint pour les supports critiques.",
        "Une certaine restriction.",
        "Contrôle d'accès lâche.",
        "Accès libre aux supports.",
    ]),
    "03.08.03": ("Comment les supports sont-ils assainis avant élimination ou réutilisation ?", [
        "L'assainissement suit des méthodes approuvées avec vérification et enregistrements pour tous les supports.",
        "Réalisé pour les supports critiques, avec enregistrements.",
        "Réalisé mais documenté de façon incohérente.",
        "Assainissement ponctuel.",
        "Les supports sont éliminés ou réutilisés sans assainissement.",
    ]),
    "03.08.04": ("Les supports et impressions portent-ils les marquages CUI appropriés ?", [
        "Le marquage est normalisé, appliqué et vérifié sur les supports et impressions.",
        "Appliqué pour les supports critiques.",
        "Appliqué de façon incohérente.",
        "Rarement appliqué.",
        "Aucun marquage.",
    ]),
    "03.08.05": ("Comment les supports sont-ils protégés pendant le transport ?", [
        "Le transport est autorisé, chiffré, suivi et journalisé.",
        "Contrôlé pour les supports critiques.",
        "Contrôles de transport de base.",
        "Contrôle minimal.",
        "Transport non contrôlé.",
    ]),
    "03.08.07": ("Comment l'usage des supports amovibles est-il contrôlé ?", [
        "L'usage des supports amovibles est restreint/chiffré et techniquement imposé (ou interdit).",
        "Contrôlé sur les systèmes critiques.",
        "Une politique existe; l'application est partielle.",
        "Peu contrôlé.",
        "Supports amovibles sans restriction.",
    ]),
    "03.08.09": ("Comment la confidentialité des CUI dans les sauvegardes est-elle protégée (p. ex. chiffrement des sauvegardes) ?", [
        "Toutes les sauvegardes de CUI sont chiffrées avec une cryptographie validée et à accès contrôlé, sur site et hors site, et vérifiées.",
        "Les sauvegardes des CUI critiques sont chiffrées et à accès contrôlé; quelques jeux de sauvegarde ne sont pas encore couverts.",
        "Des sauvegardes existent et certaines sont chiffrées, mais la protection de la confidentialité est incohérente.",
        "Les sauvegardes sont en grande partie non chiffrées ou faiblement protégées.",
        "Les sauvegardes contenant des CUI sont stockées sans aucune protection de la confidentialité.",
    ]),
    # ── 03.09 Sécurité du personnel ───────────────────────────────────
    "03.09.01": ("Le personnel est-il vérifié avant d'obtenir l'accès aux CUI ?", [
        "La vérification est exigée, basée sur le risque, revalidée et suivie pour tous les rôles avec accès aux CUI.",
        "Exigée pour les rôles critiques.",
        "Réalisée de façon incohérente.",
        "Rarement réalisée.",
        "Aucune vérification.",
    ]),
    "03.09.02": ("À quelle vitesse l'accès est-il retiré au départ ou à la mutation d'un employé ?", [
        "Les changements d'accès sont automatisés et immédiats sur déclencheurs RH, avec vérification.",
        "Rapides et documentés pour les accès critiques.",
        "Gérés mais avec des délais.",
        "Lents ou ponctuels.",
        "L'accès n'est pas retiré de façon fiable.",
    ]),
    # ── 03.10 Protection physique ─────────────────────────────────────
    "03.10.01": ("Comment les autorisations d'accès physique sont-elles gérées ?", [
        "Les autorisations sont gérées formellement, au moindre privilège et révisées régulièrement.",
        "Gérées pour les zones critiques.",
        "Gestion de base.",
        "Informel.",
        "Aucun contrôle des autorisations d'accès physique.",
    ]),
    "03.10.02": ("L'accès physique est-il surveillé et journalisé ?", [
        "Surveillance continue (CCTV/journaux) avec révision et alerte.",
        "Surveillé pour les zones critiques.",
        "Une certaine surveillance.",
        "Surveillance minimale.",
        "Aucune surveillance de l'accès physique.",
    ]),
    "03.10.06": ("Des contrôles de sécurité sont-ils appliqués aux sites de travail alternatifs/distants ?", [
        "Les contrôles pour le télétravail sont définis, appliqués et vérifiés.",
        "Appliqués pour les rôles critiques.",
        "Des consignes de base existent.",
        "Ponctuel.",
        "Aucun contrôle pour les sites de travail alternatifs.",
    ]),
    "03.10.07": ("Comment l'accès physique aux installations et systèmes est-il contrôlé ?", [
        "Des contrôles physiques en couches sont appliqués et audités pour toutes les zones sensibles.",
        "Appliqués pour les zones critiques.",
        "Contrôles de base sur les zones clés.",
        "Contrôle minimal.",
        "Accès physique non contrôlé.",
    ]),
    "03.10.08": ("Les périphériques de sortie (écrans, imprimantes, numériseurs, copieurs) sont-ils placés et contrôlés pour que des personnes non autorisées ne puissent voir ou récupérer des CUI ?", [
        "Le placement et l'accès aux périphériques de sortie sont contrôlés et vérifiés partout où des CUI sont affichés ou imprimés, avec impression sécurisée imposée.",
        "Contrôlés pour les zones critiques (écrans protégés, impression sécurisée); des lacunes subsistent dans les zones secondaires.",
        "Mesures de base sur les périphériques clés, appliquées de façon incohérente.",
        "Peu de contrôle sur qui peut voir ou récupérer les sorties CUI.",
        "Périphériques de sortie non protégés; les CUI à l'écran et imprimés sont exposés ouvertement.",
    ]),
    # ── 03.11 Évaluation des risques ──────────────────────────────────
    "03.11.01": ("Quelle est la maturité de votre processus d'évaluation des risques ?", [
        "Les évaluations de risques sont régulières, pilotées par une méthodologie et alimentent les décisions de traitement.",
        "Réalisées périodiquement pour le périmètre critique.",
        "Réalisées occasionnellement.",
        "Informelles ou ponctuelles.",
        "Aucune évaluation des risques.",
    ]),
    "03.11.02": ("Quelle est la maturité de votre surveillance et analyse des vulnérabilités ?", [
        "L'analyse authentifiée est continue sur tous les actifs, avec remédiation suivie.",
        "Analyse régulière des actifs critiques.",
        "Analyse périodique des systèmes clés.",
        "Analyse occasionnelle.",
        "Aucune analyse de vulnérabilités.",
    ]),
    "03.11.04": ("Comment les risques identifiés sont-ils traités et suivis ?", [
        "Les risques sont priorisés, traités et suivis jusqu'à clôture avec une responsabilité claire.",
        "Traités pour les risques critiques.",
        "Suivis de façon informelle.",
        "Réponse aux risques incohérente.",
        "Les risques ne sont pas traités.",
    ]),
    # ── 03.12 Évaluation de la sécurité ───────────────────────────────
    "03.12.01": ("Comment l'efficacité des contrôles de sécurité est-elle évaluée ?", [
        "Les contrôles sont évalués selon un calendrier avec résultats documentés et suivi.",
        "Évalués pour les contrôles critiques.",
        "Évaluation informelle périodique.",
        "Rarement évalués.",
        "Les contrôles ne sont jamais évalués.",
    ]),
    "03.12.02": ("Maintenez-vous un plan d'action et de jalons (POA&M) pour les écarts ?", [
        "Un POA&M est maintenu, priorisé, doté de ressources et suivi jusqu'à clôture.",
        "Maintenu pour les écarts critiques.",
        "Existe mais n'est pas activement suivi.",
        "Désuet.",
        "Aucun POA&M.",
    ]),
    "03.12.03": ("Quelle est la maturité de la surveillance continue de votre posture de sécurité ?", [
        "Une surveillance continue avec indicateurs et tableaux de bord guide les décisions.",
        "Surveillance pour les systèmes critiques.",
        "Surveillance périodique.",
        "Surveillance minimale.",
        "Aucune surveillance continue.",
    ]),
    "03.12.05": ("Les interconnexions de systèmes et échanges d'information sont-ils régis par des ententes ?", [
        "Tous les échanges et interconnexions sont autorisés et régis par des ententes à jour.",
        "Régis pour les échanges critiques.",
        "Quelques ententes existent.",
        "Arrangements informels.",
        "Aucune entente d'interconnexion.",
    ]),
    # ── 03.13 Protection des systèmes et des communications ───────────
    "03.13.01": ("Dans quelle mesure les frontières du réseau sont-elles protégées ?", [
        "Les frontières sont segmentées, en refus par défaut, et surveillées en continu avec des contrôles en couches.",
        "Protégées pour les frontières critiques.",
        "Pare-feu de base sur les frontières clés.",
        "Segmentation minimale.",
        "Réseau plat ou non protégé.",
    ]),
    "03.13.04": ("Les ressources système partagées sont-elles empêchées de laisser fuir des CUI résiduels ?", [
        "Des contrôles empêchent le transfert d'information résiduelle sur toutes les ressources partagées.",
        "Traité pour les systèmes critiques.",
        "Partiellement traité.",
        "Gestion minimale.",
        "Non traité.",
    ]),
    "03.13.06": ("Le trafic réseau est-il en refus par défaut, autorisé par exception ?", [
        "Le refus par défaut est appliqué et révisé à toutes les frontières.",
        "Appliqué aux frontières critiques.",
        "Appliqué sur les frontières clés.",
        "Surtout permissif.",
        "Politique réseau « tout autoriser ».",
    ]),
    "03.13.08": ("Dans quelle mesure les CUI sont-ils protégés par chiffrement en transit et au repos (transmission et stockage) ?", [
        "Une cryptographie forte et validée protège les CUI partout où ils sont transmis et stockés, à l'interne et à l'externe, imposée et inventoriée.",
        "Le chiffrement est imposé pour la transmission externe et les CUI stockés sur les systèmes critiques; quelques chemins internes ou dépôts subsistent.",
        "Le chiffrement est appliqué aux chemins de transmission clés et au stockage principal, mais la couverture est partielle.",
        "Le chiffrement des CUI en transit et au repos est incohérent ou faible.",
        "Les CUI sont transmis et stockés sans chiffrement.",
    ]),
    "03.13.09": ("Les connexions réseau sont-elles terminées après inactivité ?", [
        "La déconnexion réseau sur inactivité est appliquée de façon cohérente sur les systèmes.",
        "Appliquée sur les systèmes critiques.",
        "Appliquée sur les systèmes clés.",
        "Incohérente.",
        "Les connexions ne sont jamais terminées.",
    ]),
    "03.13.10": ("Comment les clés cryptographiques sont-elles établies et gérées ?", [
        "Les clés sont gérées sur tout leur cycle de vie avec génération, stockage et rotation sécurisés.",
        "Gérées pour les systèmes critiques.",
        "Gestion de clés de base.",
        "Informel.",
        "Les clés ne sont pas gérées.",
    ]),
    "03.13.11": ("Utilisez-vous une cryptographie validée (p. ex. FIPS) pour protéger les CUI ?", [
        "Une cryptographie validée FIPS est imposée partout où les CUI sont protégés, avec un inventaire.",
        "Utilisée pour les données critiques.",
        "Utilisée sur les systèmes clés.",
        "Cryptographie incohérente ou non validée.",
        "Aucune cryptographie ou cryptographie faible.",
    ]),
    "03.13.12": ("Les dispositifs de collaboration (caméras, microphones) sont-ils contrôlés ?", [
        "L'activation est contrôlée, indiquée et imposée par politique sur tous les appareils.",
        "Contrôlée sur les appareils critiques.",
        "Un certain contrôle.",
        "Contrôle minimal.",
        "Non contrôlés.",
    ]),
    "03.13.13": ("Le code mobile (scripts, applets, macros) est-il contrôlé ?", [
        "Le code mobile est régi par politique et techniquement restreint.",
        "Contrôlé sur les systèmes critiques.",
        "Un certain contrôle.",
        "Contrôle minimal.",
        "Code mobile non contrôlé.",
    ]),
    "03.13.15": ("L'authenticité des sessions de communication est-elle protégée ?", [
        "L'authenticité des sessions (p. ex. TLS, signature) est imposée sur les services.",
        "Imposée pour les services critiques.",
        "Imposée pour les services clés.",
        "Partielle.",
        "L'authenticité des sessions n'est pas protégée.",
    ]),
    # ── 03.14 Intégrité des systèmes et de l'information ──────────────
    "03.14.01": ("Quelle est la maturité de votre correction des failles : identifier, prioriser et corriger les vulnérabilités ?", [
        "La gestion des vulnérabilités et des correctifs est automatisée et continue sur tous les actifs, avec des SLA basés sur le risque qui sont mesurés et respectés de façon constante.",
        "Les correctifs sont planifiés et suivis pour les systèmes critiques selon des délais définis; la couverture des actifs de moindre priorité présente des lacunes.",
        "Les correctifs sont appliqués régulièrement aux systèmes clés mais la priorisation et le suivi sont surtout manuels.",
        "Les correctifs sont occasionnels ou réactifs, sans délais ni suivi définis.",
        "Aucun processus structuré de correction des failles; les systèmes sont rarement ou jamais corrigés.",
    ]),
    "03.14.02": ("Quelle est la maturité de votre protection contre les codes malveillants (anti-maliciel / EDR) ?", [
        "L'EDR/anti-maliciel est déployé partout, géré centralement, tenu à jour et surveillé avec réponse.",
        "Déployé sur les systèmes critiques et les postes et géré centralement.",
        "Anti-maliciel sur les systèmes clés, avec des mises à jour surtout à jour.",
        "Protection incohérente ou désuète.",
        "Aucune protection contre les codes malveillants.",
    ]),
    "03.14.03": ("Comment agissez-vous sur les alertes, avis et directives de sécurité ?", [
        "Les avis sont surveillés, triés et traités selon un processus défini.",
        "Surveillés et traités pour les problèmes critiques.",
        "Révisés périodiquement.",
        "Traités au cas par cas.",
        "Les avis ne sont pas surveillés.",
    ]),
    "03.14.06": ("Quelle est la maturité de votre surveillance des attaques et des indicateurs de compromission ?", [
        "Surveillance continue/IDS sur l'environnement avec alerte et réponse.",
        "Surveillance des systèmes et frontières critiques.",
        "Une certaine surveillance des systèmes clés.",
        "Surveillance minimale.",
        "Aucune surveillance des systèmes.",
    ]),
    "03.14.08": ("Les CUI sont-ils conservés et éliminés selon des exigences définies ?", [
        "La rétention et l'élimination sont définies, appliquées et vérifiées sur les systèmes.",
        "Appliquées pour les données critiques.",
        "Définies mais appliquées de façon incohérente.",
        "Ponctuel.",
        "Aucune gestion de la rétention.",
    ]),
    # ── 03.15 Planification ───────────────────────────────────────────
    "03.15.01": ("Les politiques et procédures de sécurité sont-elles documentées et maintenues ?", [
        "Des politiques et procédures complètes sont approuvées, maintenues et révisées régulièrement.",
        "Documentées pour les domaines critiques et révisées périodiquement.",
        "Des politiques de base existent.",
        "Politiques désuètes ou partielles.",
        "Aucune politique documentée.",
    ]),
    "03.15.02": ("Maintenez-vous un plan de sécurité du système (SSP) à jour ?", [
        "Le SSP est complet, à jour et maintenu à mesure que le système évolue.",
        "Un SSP existe et est mis à jour périodiquement.",
        "Un SSP de base existe.",
        "Un SSP désuet ou incomplet existe.",
        "Aucun SSP.",
    ]),
    "03.15.03": ("Des règles de conduite sont-elles définies et acceptées par les utilisateurs ?", [
        "Les règles de conduite sont définies, acceptées et réacceptées en cas de changement.",
        "Définies et acceptées.",
        "Définies, mais l'acceptation est incohérente.",
        "Informelles.",
        "Aucune règle de conduite.",
    ]),
    # ── 03.16 Acquisition de systèmes et de services ──────────────────
    "03.16.01": ("Des principes d'ingénierie de sécurité sont-ils appliqués lors de la construction et des changements de systèmes ?", [
        "Les principes de sécurité dès la conception sont appliqués et vérifiés sur tout le cycle de vie du système.",
        "Appliqués pour les systèmes critiques.",
        "Parfois appliqués.",
        "Rarement appliqués.",
        "Non appliqués.",
    ]),
    "03.16.02": ("Comment gérez-vous les composants non pris en charge / en fin de vie ?", [
        "Les composants en fin de vie sont suivis et remplacés ou atténués de façon proactive.",
        "Suivis pour les systèmes critiques.",
        "Gérés de façon réactive.",
        "Gestion minimale.",
        "Des composants non pris en charge fonctionnent sans gestion.",
    ]),
    "03.16.03": ("Les exigences de sécurité des fournisseurs de services externes sont-elles définies et surveillées ?", [
        "Les exigences de sécurité des fournisseurs sont définies, contractuelles et surveillées.",
        "Définies pour les fournisseurs critiques.",
        "Quelques exigences définies.",
        "Informel.",
        "Aucune exigence pour les fournisseurs externes.",
    ]),
    # ── 03.17 Gestion des risques de la chaîne d'approvisionnement ────
    "03.17.01": ("Avez-vous un plan de gestion des risques de la chaîne d'approvisionnement (SCRM) ?", [
        "Un plan SCRM maintenu régit les décisions d'approvisionnement et est révisé régulièrement.",
        "Un plan existe pour la chaîne d'approvisionnement critique.",
        "Un plan de base existe.",
        "Informel.",
        "Aucun plan SCRM.",
    ]),
    "03.17.02": ("Des contrôles de chaîne d'approvisionnement sont-ils appliqués aux décisions d'acquisition ?", [
        "Des contrôles et outils de chaîne d'approvisionnement sont intégrés aux décisions d'acquisition.",
        "Appliqués aux acquisitions critiques.",
        "Parfois appliqués.",
        "Rarement appliqués.",
        "Aucun contrôle de chaîne d'approvisionnement dans les acquisitions.",
    ]),
    "03.17.03": ("Les exigences de sécurité sont-elles transmises aux fournisseurs et vérifiées ?", [
        "Les exigences sont transmises, vérifiées et surveillées chez les fournisseurs.",
        "Transmises aux fournisseurs critiques.",
        "Une certaine transmission.",
        "Informel.",
        "Aucune transmission des exigences.",
    ]),
}
