"""Expert-authored, control-specific maturity self-assessment banks.

NIST SP 800-171r3. One control-specific 5-rung ladder question per control,
keyed by control ref. Each value is (prompt, [s5, s4, s3, s2, s1]) where the
statements run highest maturity (Optimized, 5) → lowest (None, 1).

Consumed by app.seed_maturity_questions. Controls not listed keep the generic
generated ladder; 03.14.09 (non-standard slot) is intentionally omitted.
"""

NIST_171R3: dict[str, tuple[str, list[str]]] = {
    # ── 03.01 Access Control ──────────────────────────────────────────
    "03.01.01": ("How mature is your account management, covering provisioning, review, and deprovisioning of system and application accounts?", [
        "Account lifecycle is automated and centrally governed across all systems; access is role-based, recertified on a schedule, and every change is logged and alerted.",
        "Documented procedures are enforced for critical systems with regular access reviews; coverage of minor systems is incomplete.",
        "Procedures are followed for key systems, but provisioning/deprovisioning and reviews are largely manual and inconsistent.",
        "Accounts are created and removed ad-hoc per system, with no standard process or periodic review.",
        "No defined account-management process; access is granted informally and rarely revoked.",
    ]),
    "03.01.02": ("How consistently is access to systems and CUI enforced against approved authorizations?", [
        "Access enforcement is centrally managed and policy-driven across all systems, with role-based rules and continuous verification.",
        "Enforced through central controls for critical systems; a few systems rely on local configuration.",
        "Access rules are applied for key systems but managed system-by-system.",
        "Enforcement is inconsistent and manually configured per system.",
        "No consistent access enforcement; permissions are open or undefined.",
    ]),
    "03.01.03": ("How well do you control the flow of CUI between systems and networks (segmentation, egress rules)?", [
        "Flow controls (segmentation, egress filtering, DLP) are enforced and monitored across all boundaries.",
        "Enforced at key boundaries for critical data; some paths are unmonitored.",
        "Basic segmentation and egress rules exist for important systems.",
        "Minimal, ad-hoc control over information flow.",
        "No control over how information moves between systems.",
    ]),
    "03.01.04": ("How well are duties separated so no single person can misuse critical functions?", [
        "Separation of duties is defined, enforced by tooling, and reviewed regularly across all critical processes.",
        "Enforced for critical functions; some conflicts remain in minor processes.",
        "Defined for key functions but enforced manually.",
        "Informal awareness of separation of duties with little enforcement.",
        "No separation of duties.",
    ]),
    "03.01.05": ("How well do you limit user and system access to only what is needed (least privilege)?", [
        "Least privilege is enforced everywhere with periodic recertification and just-in-time access.",
        "Enforced for critical systems with periodic reviews.",
        "Applied for key systems but reviews are infrequent.",
        "Broad access is common; least privilege is aspirational.",
        "Users generally have far more access than needed.",
    ]),
    "03.01.06": ("How well are privileged (administrator) accounts restricted and controlled?", [
        "Privileged access is minimized, brokered/just-in-time, MFA-protected, and fully logged and reviewed.",
        "Admin accounts are limited and MFA-protected for critical systems, with logging in place.",
        "Admin accounts are identified and somewhat limited, but shared or broadly used in places.",
        "Privileged access is loosely controlled.",
        "Admin rights are widely or permanently assigned.",
    ]),
    "03.01.07": ("How well is the use of privileged functions restricted and logged?", [
        "Privileged functions are restricted to authorized roles and every use is logged and alerted.",
        "Restricted and logged for critical systems.",
        "Restricted for key systems; logging is partial.",
        "Limited restriction or logging of privileged actions.",
        "Privileged functions are unrestricted and unlogged.",
    ]),
    "03.01.08": ("How are repeated unsuccessful logon attempts handled?", [
        "Lockout/throttling is enforced and monitored on all systems, with alerting on attack patterns.",
        "Enforced on critical systems and central identity.",
        "Configured on key systems.",
        "Inconsistent or left at defaults.",
        "No limit on failed logon attempts.",
    ]),
    "03.01.09": ("Do systems display an approved use/consent notification before granting access?", [
        "Approved banners are enforced on all access paths and kept current with policy.",
        "Displayed on critical and remote-access systems.",
        "Present on some systems.",
        "Rarely used.",
        "No system-use notification.",
    ]),
    "03.01.10": ("How are sessions locked after a period of inactivity (device lock)?", [
        "Automatic session/device lock is enforced everywhere with appropriate timeouts.",
        "Enforced on critical systems and most endpoints.",
        "Configured on key systems.",
        "Inconsistent; relies on users.",
        "No session lock.",
    ]),
    "03.01.11": ("Are user sessions terminated after defined conditions or inactivity?", [
        "Automatic session termination is enforced consistently across systems and applications.",
        "Enforced for critical systems and remote access.",
        "Applied to key systems.",
        "Inconsistent.",
        "Sessions never time out.",
    ]),
    "03.01.12": ("How well is remote access secured, authorized, and monitored?", [
        "All remote access is brokered through hardened, MFA-protected, fully monitored channels with no split tunneling.",
        "Secured and MFA-protected for staff and monitored centrally, with minor gaps.",
        "VPN/remote access exists with MFA on key paths but limited monitoring.",
        "Remote access is allowed with only basic controls.",
        "Remote access is uncontrolled or unmonitored.",
    ]),
    "03.01.16": ("How well is wireless access secured and authorized?", [
        "Wireless is segmented, strongly authenticated (e.g. 802.1X), and continuously monitored, with rogue-AP detection.",
        "Enterprise wireless is encrypted and authenticated, with monitoring in place.",
        "Wireless is secured with WPA2/3 and passwords, with limited monitoring.",
        "Basic wireless security; guest and corporate networks are not separated.",
        "Open or weakly secured wireless.",
    ]),
    "03.01.18": ("How well are mobile devices managed and controlled?", [
        "All mobile devices are MDM-enrolled, encrypted, policy-enforced, and remotely wipeable.",
        "Managed and encrypted for company devices; BYOD partially covered.",
        "Basic mobile controls on key devices.",
        "Minimal mobile device control.",
        "No mobile device controls.",
    ]),
    "03.01.20": ("How well do you govern use of external systems and services for CUI?", [
        "External system/service use is governed by policy, approved, and technically restricted, with sanctioned alternatives.",
        "Governed for critical data; some shadow IT remains.",
        "Policy exists but enforcement is limited.",
        "Little governance of external systems.",
        "No control over use of external systems.",
    ]),
    "03.01.22": ("How do you ensure CUI is never posted to publicly accessible systems?", [
        "Content is reviewed and approved before publishing, with periodic scans for inadvertent disclosure.",
        "A review process is in place for public content.",
        "Informal review before posting.",
        "Little review of public content.",
        "No control over publicly posted content.",
    ]),
    # ── 03.02 Awareness & Training ────────────────────────────────────
    "03.02.01": ("How mature is your security literacy and awareness program?", [
        "Awareness is continuous and measured (e.g. phishing simulations), refreshed and tracked for all staff.",
        "Annual training for all staff plus periodic reminders, with completion tracked.",
        "Annual training exists but tracking and refresh are inconsistent.",
        "Occasional, ad-hoc awareness activity.",
        "No security awareness training.",
    ]),
    "03.02.02": ("How mature is role-based training for staff with security responsibilities?", [
        "Role-based training is defined, delivered, and tracked for every security-relevant role and refreshed regularly.",
        "Delivered for key roles, with tracking in place.",
        "Some role-based training, inconsistently delivered.",
        "Rare role-specific training.",
        "No role-based training.",
    ]),
    # ── 03.03 Audit & Accountability ──────────────────────────────────
    "03.03.01": ("How mature is your security event logging: what you log, where it goes, and how long it is kept?", [
        "Logging is centralized (SIEM), covers all in-scope systems and the defined event types, with enforced retention, integrity protection, and time synchronization.",
        "Critical systems log the required events to a central store with defined retention; some lower-tier systems or event types are not covered yet.",
        "Key systems generate and retain logs, but collection is partly local/manual and the event set is not standardized.",
        "Logging is on in places but ad-hoc and inconsistent, and is not centrally collected or reviewed.",
        "Little or no security event logging is in place.",
    ]),
    "03.03.02": ("Do audit records capture enough detail (who, what, when, where, outcome)?", [
        "Log content is standardized to capture all required fields across systems and is validated.",
        "Critical systems capture the required detail; minor systems vary.",
        "Key systems log core fields, but content is not standardized.",
        "Logs lack consistent detail.",
        "Logs contain minimal or no useful detail.",
    ]),
    "03.03.03": ("Are auditable events defined and reliably generated across systems?", [
        "Auditable events are defined organization-wide and generated and verified on all in-scope systems.",
        "Defined and generated for critical systems.",
        "Generated on key systems, but the event set is not formally defined.",
        "Ad-hoc audit generation.",
        "No defined audit generation.",
    ]),
    "03.03.04": ("What happens when audit logging fails?", [
        "Logging failures trigger automated alerts and a defined response, and are monitored continuously.",
        "Alerts exist for critical systems.",
        "Failures are noticed during periodic checks.",
        "Failures are rarely detected.",
        "No detection of logging failures.",
    ]),
    "03.03.05": ("How are audit logs reviewed, analyzed, and reported on?", [
        "Centralized correlation and analysis with regular reporting and tuned alerting.",
        "Regular review of critical logs, partly automated.",
        "Periodic manual review of key logs.",
        "Logs reviewed only after incidents.",
        "Logs are not reviewed.",
    ]),
    "03.03.06": ("Can you efficiently search, reduce, and report on audit data?", [
        "Tooling supports on-demand search, reduction, and reporting without altering originals.",
        "Available for critical systems.",
        "Basic search on key logs.",
        "Manual and limited.",
        "No reduction or reporting capability.",
    ]),
    "03.03.07": ("Are system clocks synchronized and timestamps reliable?", [
        "All systems synchronize to an authoritative time source, verified.",
        "Critical systems are synchronized.",
        "Key systems are synchronized.",
        "Time synchronization is inconsistent.",
        "No time synchronization.",
    ]),
    "03.03.08": ("How are audit logs protected from tampering or deletion?", [
        "Logs are write-once or centralized, with access restricted and integrity monitored.",
        "Protected and access-controlled for critical logs.",
        "Some protection on key logs.",
        "Logs stored locally with weak protection.",
        "Logs are unprotected.",
    ]),
    # ── 03.04 Configuration Management ────────────────────────────────
    "03.04.01": ("How well are secure baseline configurations defined and maintained?", [
        "Hardened baselines are defined, version-controlled, and enforced/automated for all system types.",
        "Baselines are defined and applied to critical systems.",
        "Baselines exist for key systems, but drift is not tracked.",
        "Informal baselines.",
        "No defined baselines.",
    ]),
    "03.04.02": ("Are secure configuration settings enforced (e.g. CIS/STIG benchmarks)?", [
        "Settings are enforced to a recognized benchmark and continuously monitored for drift.",
        "Enforced on critical systems.",
        "Applied to key systems.",
        "Some hardening, inconsistently applied.",
        "Default or unmanaged settings.",
    ]),
    "03.04.03": ("How are changes to systems controlled and approved?", [
        "All changes go through a formal change-control process with approval, testing, and records.",
        "Change control is in place for critical systems.",
        "A basic change process exists for key systems.",
        "Changes are made informally.",
        "No change control.",
    ]),
    "03.04.04": ("Are security impacts analyzed before changes are made?", [
        "Security impact analysis is required and documented for all changes.",
        "Performed for critical changes.",
        "Sometimes performed.",
        "Rarely performed.",
        "Never performed.",
    ]),
    "03.04.05": ("Is the ability to make changes restricted and logged?", [
        "Change access is least-privilege, enforced, and fully logged.",
        "Restricted and logged on critical systems.",
        "Restricted on key systems.",
        "Loosely controlled.",
        "Anyone can change systems.",
    ]),
    "03.04.06": ("Are systems configured to provide only essential capabilities (least functionality)?", [
        "Unneeded ports, services, and functions are disabled and continuously verified everywhere.",
        "Hardened for critical systems.",
        "Key systems are hardened.",
        "Some hardening.",
        "Systems run default services.",
    ]),
    "03.04.08": ("How do you control which software can be installed and run (allowlisting)?", [
        "Application allowlisting is enforced and maintained across endpoints and servers.",
        "Allowlisting on critical systems; others use blocklists.",
        "Software is controlled on key systems.",
        "Limited control over software.",
        "Any software can be installed or run.",
    ]),
    "03.04.10": ("How complete and current is your system component (asset) inventory?", [
        "An automated, continuously reconciled inventory covers all components and CUI assets.",
        "A maintained inventory of critical assets is updated regularly.",
        "An inventory exists but is updated periodically or manually.",
        "Partial or outdated inventory.",
        "No inventory.",
    ]),
    "03.04.11": ("Do you know where CUI is stored, processed, and transmitted?", [
        "CUI locations are mapped, tracked, and verified continuously.",
        "Known for critical repositories.",
        "Generally known for key systems.",
        "Partially known.",
        "CUI location is unknown.",
    ]),
    "03.04.12": ("Are devices configured for higher-risk situations (e.g. travel)?", [
        "Hardened high-risk/travel configurations are defined and enforced, with post-travel checks.",
        "Applied for known high-risk cases.",
        "Some guidance exists.",
        "Handled ad-hoc.",
        "No special configuration for high-risk situations.",
    ]),
    # ── 03.05 Identification & Authentication ─────────────────────────
    "03.05.01": ("How robustly are users uniquely identified and authenticated?", [
        "Unique IDs and strong, phishing-resistant authentication are enforced for all users and systems centrally.",
        "Unique IDs and strong authentication for critical systems.",
        "Unique IDs, but authentication strength varies.",
        "Shared accounts exist.",
        "Weak or shared identification.",
    ]),
    "03.05.02": ("Are devices identified and authenticated before network access?", [
        "Device authentication (802.1X/certificates) is enforced and monitored network-wide.",
        "Enforced on critical segments.",
        "Enforced on key segments.",
        "Limited device authentication.",
        "No device authentication.",
    ]),
    "03.05.03": ("How mature is your use of multi-factor authentication for access to systems and accounts?", [
        "Phishing-resistant MFA is enforced for all users and every access path (remote, privileged, local, and applications), with no unmanaged exceptions.",
        "MFA is enforced for remote and privileged access and most applications; a few legacy systems or exceptions remain.",
        "MFA is enabled for key systems (e.g. VPN, email) but coverage is partial and not consistently enforced.",
        "MFA is available but optional, or used only by some users or systems.",
        "No multi-factor authentication is in use; access relies on passwords alone.",
    ]),
    "03.05.04": ("Is authentication resistant to replay attacks?", [
        "Replay-resistant mechanisms are enforced for all privileged and network access.",
        "Enforced for critical and remote access.",
        "Enforced for key systems.",
        "Limited.",
        "No replay resistance.",
    ]),
    "03.05.05": ("How are identifiers issued, managed, and retired?", [
        "Identifier lifecycle is formally managed and reuse is prevented across systems.",
        "Managed for critical systems.",
        "Managed for key systems.",
        "Informal.",
        "Unmanaged identifiers.",
    ]),
    "03.05.07": ("How strong is your password and credential management?", [
        "Policy enforces strong, screened passwords, secure storage, and rotation only on compromise, aligned to current guidance.",
        "A strong policy is enforced on critical systems.",
        "A basic policy is applied to key systems.",
        "Weak or inconsistent password policy.",
        "No password policy.",
    ]),
    "03.05.11": ("Is authentication feedback obscured (e.g. masked passwords)?", [
        "Feedback is obscured across all systems by standard.",
        "Obscured on critical systems.",
        "Obscured on key systems.",
        "Inconsistent.",
        "Credentials may be exposed during entry.",
    ]),
    "03.05.12": ("How are authenticators (tokens, certificates, keys) managed?", [
        "Full lifecycle management with secure issuance, storage, rotation, and revocation.",
        "Managed for critical systems.",
        "Managed for key systems.",
        "Informal.",
        "Unmanaged authenticators.",
    ]),
    # ── 03.06 Incident Response ───────────────────────────────────────
    "03.06.01": ("How mature is your incident handling capability across preparation, detection, analysis, containment, and recovery?", [
        "A documented IR plan is exercised regularly (tabletops/drills), with defined roles, tooling, and post-incident reviews that feed continuous improvement.",
        "A formal IR plan and team exist and are used for real incidents; testing happens but not on a regular cadence.",
        "Basic incident procedures are documented for common scenarios, but roles, tooling, or testing are limited.",
        "Incidents are handled reactively and informally, with no documented plan.",
        "No incident-handling process; incidents are addressed ad-hoc, if noticed at all.",
    ]),
    "03.06.02": ("How are incidents tracked and reported internally and externally?", [
        "Incidents are centrally tracked with defined internal and external (incl. regulator) reporting and metrics.",
        "Tracked and reported for significant incidents.",
        "Basic tracking; reporting is informal.",
        "Reactive, with minimal tracking.",
        "No tracking or reporting.",
    ]),
    "03.06.03": ("How is the incident response capability tested?", [
        "Regular, scenario-based exercises with documented improvements.",
        "Periodic testing.",
        "Occasional or informal testing.",
        "Rarely tested.",
        "Never tested.",
    ]),
    "03.06.04": ("Are incident responders trained for their roles?", [
        "Role-based IR training is delivered and refreshed for all responders.",
        "Delivered to key responders.",
        "Some training.",
        "Rare training.",
        "No responder training.",
    ]),
    "03.06.05": ("Do you maintain a current, distributed incident response plan?", [
        "The IR plan is documented, maintained, distributed, and updated after incidents and changes.",
        "A documented plan is updated periodically.",
        "A basic plan exists.",
        "An outdated or partial plan exists.",
        "No IR plan.",
    ]),
    # ── 03.07 Maintenance ─────────────────────────────────────────────
    # 03.07.01 has no standalone r3 control; authored so CMMC MA.L2-3.7.1
    # (general system maintenance, from 800-171 r2) gets a control-specific
    # question instead of the generic ladder. Unused by NIST r3 / ITSP.
    "03.07.01": ("How mature is your system maintenance program (scheduling, performing, and recording maintenance)?", [
        "Maintenance is scheduled, performed, and documented under a controlled process for all systems, with approvals and records.",
        "Controlled, documented maintenance for critical systems; some systems are handled ad-hoc.",
        "Maintenance happens for key systems, but scheduling and records are inconsistent.",
        "Maintenance is reactive and rarely documented.",
        "No managed maintenance process.",
    ]),
    "03.07.04": ("Are maintenance tools controlled and inspected?", [
        "Tools are approved, inspected, and controlled, and media is scanned before use.",
        "Controlled for critical systems.",
        "Basic control of maintenance tools.",
        "Minimal control.",
        "Uncontrolled maintenance tools.",
    ]),
    "03.07.05": ("How is remote (nonlocal) maintenance secured?", [
        "Remote maintenance is authorized, MFA-protected, logged, and terminated after use.",
        "Secured for critical systems.",
        "Some controls in place.",
        "Loosely controlled.",
        "Uncontrolled remote maintenance.",
    ]),
    "03.07.06": ("Are maintenance personnel authorized and supervised?", [
        "Personnel are vetted, authorized, and escorted/supervised, with access logged.",
        "Controlled for critical systems.",
        "Basic checks.",
        "Minimal control.",
        "No control over maintenance personnel.",
    ]),
    # ── 03.08 Media Protection ────────────────────────────────────────
    "03.08.01": ("How is media containing CUI stored and protected?", [
        "Media is inventoried, encrypted/secured, and access-controlled across all locations.",
        "Secured for critical media.",
        "Basic protection for key media.",
        "Inconsistent protection.",
        "Media is unprotected.",
    ]),
    "03.08.02": ("Is access to media containing CUI restricted?", [
        "Access is restricted to authorized roles and logged.",
        "Restricted for critical media.",
        "Some restriction.",
        "Loose access control.",
        "Open access to media.",
    ]),
    "03.08.03": ("How is media sanitized before disposal or reuse?", [
        "Sanitization follows approved methods with verification and records for all media.",
        "Performed for critical media, with records.",
        "Performed but inconsistently documented.",
        "Ad-hoc sanitization.",
        "Media is disposed of or reused without sanitization.",
    ]),
    "03.08.04": ("Is media and output marked with appropriate CUI markings?", [
        "Marking is standardized and applied and verified across media and output.",
        "Applied for critical media.",
        "Applied inconsistently.",
        "Rarely applied.",
        "No marking.",
    ]),
    "03.08.05": ("How is media protected during transport?", [
        "Transport is authorized, encrypted, tracked, and logged.",
        "Controlled for critical media.",
        "Basic transport controls.",
        "Minimal control.",
        "Uncontrolled transport.",
    ]),
    "03.08.07": ("How is the use of removable media controlled?", [
        "Removable media use is restricted/encrypted and technically enforced (or prohibited).",
        "Controlled on critical systems.",
        "Policy exists; enforcement is partial.",
        "Loosely controlled.",
        "Unrestricted removable media.",
    ]),
    "03.08.09": ("How is the confidentiality of CUI in backups protected (e.g. encryption of backup data)?", [
        "All CUI backups are encrypted with validated cryptography and access-controlled, on-site and off-site, and verified.",
        "Backups of critical CUI are encrypted and access-controlled; a few backup sets are not yet covered.",
        "Backups exist and some are encrypted, but confidentiality protection is inconsistent.",
        "Backups are largely unencrypted or only weakly protected.",
        "Backups containing CUI are stored without any confidentiality protection.",
    ]),
    # ── 03.09 Personnel Security ──────────────────────────────────────
    "03.09.01": ("Are personnel screened before being granted CUI access?", [
        "Screening is required, risk-based, re-validated, and tracked for all CUI roles.",
        "Required for critical roles.",
        "Performed inconsistently.",
        "Rarely performed.",
        "No screening.",
    ]),
    "03.09.02": ("How quickly is access removed on personnel termination or transfer?", [
        "Access changes are automated and immediate on HR triggers, with verification.",
        "Prompt and documented for critical access.",
        "Handled but with delays.",
        "Slow or ad-hoc.",
        "Access is not reliably removed.",
    ]),
    # ── 03.10 Physical Protection ─────────────────────────────────────
    "03.10.01": ("How are physical access authorizations managed?", [
        "Authorizations are formally managed, least-privilege, and reviewed regularly.",
        "Managed for critical areas.",
        "Basic management.",
        "Informal.",
        "No control over physical access authorizations.",
    ]),
    "03.10.02": ("Is physical access monitored and logged?", [
        "Continuous monitoring (CCTV/logs) with review and alerting.",
        "Monitored for critical areas.",
        "Some monitoring.",
        "Minimal monitoring.",
        "No physical access monitoring.",
    ]),
    "03.10.06": ("Are security controls applied at alternate/remote work sites?", [
        "Remote-work controls are defined, enforced, and verified.",
        "Applied for critical roles.",
        "Basic guidance exists.",
        "Ad-hoc.",
        "No alternate-work-site controls.",
    ]),
    "03.10.07": ("How is physical access to facilities and systems controlled?", [
        "Layered physical controls are enforced and audited for all sensitive areas.",
        "Enforced for critical areas.",
        "Basic controls on key areas.",
        "Minimal control.",
        "Uncontrolled physical access.",
    ]),
    "03.10.08": ("Are output devices (monitors, printers, scanners, copiers) positioned and controlled so unauthorized people cannot view or collect CUI?", [
        "Output-device placement and access are controlled and verified everywhere CUI is displayed or printed, with secure/pull printing enforced.",
        "Controlled for critical areas (screens shielded, secure printing); minor areas have gaps.",
        "Basic measures on key devices, applied inconsistently.",
        "Little control over who can view or collect CUI output.",
        "Output devices are unprotected; CUI on screens and printouts is openly exposed.",
    ]),
    # ── 03.11 Risk Assessment ─────────────────────────────────────────
    "03.11.01": ("How mature is your risk assessment process?", [
        "Risk assessments are regular, methodology-driven, and feed treatment decisions.",
        "Conducted periodically for critical scope.",
        "Conducted occasionally.",
        "Informal or ad-hoc.",
        "No risk assessments.",
    ]),
    "03.11.02": ("How mature is your vulnerability monitoring and scanning?", [
        "Authenticated scanning is continuous across all assets, with tracked remediation.",
        "Regular scanning of critical assets.",
        "Periodic scanning of key systems.",
        "Occasional scanning.",
        "No vulnerability scanning.",
    ]),
    "03.11.04": ("How are identified risks treated and tracked?", [
        "Risks are prioritized, treated, and tracked to closure with clear accountability.",
        "Treated for critical risks.",
        "Tracked informally.",
        "Inconsistent risk response.",
        "Risks are not addressed.",
    ]),
    # ── 03.12 Security Assessment ─────────────────────────────────────
    "03.12.01": ("How are security controls assessed for effectiveness?", [
        "Controls are assessed on a schedule with documented results and follow-up.",
        "Assessed for critical controls.",
        "Periodic informal assessment.",
        "Rarely assessed.",
        "Controls are never assessed.",
    ]),
    "03.12.02": ("Do you maintain a Plan of Action & Milestones (POA&M) for gaps?", [
        "A POA&M is maintained, prioritized, resourced, and tracked to closure.",
        "Maintained for critical gaps.",
        "Exists but not actively tracked.",
        "Outdated.",
        "No POA&M.",
    ]),
    "03.12.03": ("How mature is continuous monitoring of your security posture?", [
        "Continuous monitoring with metrics and dashboards drives ongoing decisions.",
        "Monitoring for critical systems.",
        "Periodic monitoring.",
        "Minimal monitoring.",
        "No continuous monitoring.",
    ]),
    "03.12.05": ("Are system interconnections and information exchanges governed by agreements?", [
        "All exchanges and interconnections are authorized and governed by current agreements.",
        "Governed for critical exchanges.",
        "Some agreements exist.",
        "Informal arrangements.",
        "No interconnection agreements.",
    ]),
    # ── 03.13 System & Communications Protection ──────────────────────
    "03.13.01": ("How well are network boundaries protected?", [
        "Boundaries are segmented, default-deny, and continuously monitored with layered controls.",
        "Protected for critical boundaries.",
        "Basic firewalling on key boundaries.",
        "Minimal segmentation.",
        "Flat or unprotected network.",
    ]),
    "03.13.04": ("Are shared system resources prevented from leaking residual CUI?", [
        "Controls prevent residual information transfer across all shared resources.",
        "Addressed for critical systems.",
        "Partially addressed.",
        "Minimal handling.",
        "Not addressed.",
    ]),
    "03.13.06": ("Is network traffic deny-all, permit-by-exception?", [
        "Default-deny is enforced and reviewed at all boundaries.",
        "Enforced at critical boundaries.",
        "Applied on key boundaries.",
        "Mostly permissive.",
        "Allow-all network policy.",
    ]),
    "03.13.08": ("How well is CUI protected with encryption both in transit and at rest (transmission and storage)?", [
        "Strong, validated cryptography protects CUI everywhere it is transmitted and stored, internal and external, enforced and inventoried.",
        "Encryption is enforced for external transmission and for stored CUI on critical systems; a few internal paths or repositories remain.",
        "Encryption is applied on key transmission paths and primary storage, but coverage is partial.",
        "Encryption of CUI in transit and at rest is inconsistent or weak.",
        "CUI is transmitted and stored without encryption.",
    ]),
    "03.13.09": ("Are network connections terminated after inactivity?", [
        "Network disconnect on inactivity is enforced consistently across systems.",
        "Enforced on critical systems.",
        "Enforced on key systems.",
        "Inconsistent.",
        "Connections are never terminated.",
    ]),
    "03.13.10": ("How are cryptographic keys established and managed?", [
        "Keys are managed through their full lifecycle with secure generation, storage, and rotation.",
        "Managed for critical systems.",
        "Basic key management.",
        "Informal.",
        "Keys are unmanaged.",
    ]),
    "03.13.11": ("Do you use validated (e.g. FIPS) cryptography to protect CUI?", [
        "FIPS-validated cryptography is enforced wherever CUI is protected, with an inventory.",
        "Used for critical data.",
        "Used on key systems.",
        "Inconsistent or unvalidated cryptography.",
        "No or weak cryptography.",
    ]),
    "03.13.12": ("Are collaborative computing devices (cameras, microphones) controlled?", [
        "Activation is controlled, indicated, and policy-enforced on all devices.",
        "Controlled on critical devices.",
        "Some control.",
        "Minimal control.",
        "Uncontrolled.",
    ]),
    "03.13.13": ("Is mobile code (scripts, applets, macros) controlled?", [
        "Mobile code is governed by policy and technically restricted.",
        "Controlled on critical systems.",
        "Some control.",
        "Minimal control.",
        "Uncontrolled mobile code.",
    ]),
    "03.13.15": ("Is the authenticity of communications sessions protected?", [
        "Session authenticity (e.g. TLS, signing) is enforced across services.",
        "Enforced for critical services.",
        "Enforced for key services.",
        "Partial.",
        "Session authenticity is not protected.",
    ]),
    # ── 03.14 System & Information Integrity ──────────────────────────
    "03.14.01": ("How mature is your flaw remediation: identifying, prioritising, and patching vulnerabilities?", [
        "Vulnerability and patch management is automated and continuous across all assets, with risk-based SLAs that are measured and consistently met.",
        "Patching is scheduled and tracked for critical systems against defined timelines; coverage of lower-priority assets has gaps.",
        "Patching happens regularly for key systems but prioritisation and tracking are largely manual.",
        "Patching is occasional or reactive, with no defined timelines or tracking.",
        "No structured flaw-remediation process; systems are patched rarely or not at all.",
    ]),
    "03.14.02": ("How mature is your malicious-code protection (anti-malware / EDR)?", [
        "EDR/anti-malware is deployed everywhere, centrally managed, kept current, and monitored with response.",
        "Deployed on critical systems and endpoints and managed centrally.",
        "Anti-malware on key systems, with mostly current updates.",
        "Inconsistent or outdated protection.",
        "No malicious-code protection.",
    ]),
    "03.14.03": ("How do you act on security alerts, advisories, and directives?", [
        "Advisories are monitored, triaged, and actioned through a defined process.",
        "Monitored and actioned for critical issues.",
        "Reviewed periodically.",
        "Acted on ad-hoc.",
        "Advisories are not monitored.",
    ]),
    "03.14.06": ("How mature is your monitoring for attacks and indicators of compromise?", [
        "Continuous monitoring/IDS across the environment with alerting and response.",
        "Monitoring on critical systems and boundaries.",
        "Some monitoring on key systems.",
        "Minimal monitoring.",
        "No system monitoring.",
    ]),
    "03.14.08": ("Is CUI retained and disposed of according to defined requirements?", [
        "Retention and disposal are defined, enforced, and verified across systems.",
        "Enforced for critical data.",
        "Defined but inconsistently applied.",
        "Ad-hoc.",
        "No retention management.",
    ]),
    # ── 03.15 Planning ────────────────────────────────────────────────
    "03.15.01": ("Are security policies and procedures documented and maintained?", [
        "Comprehensive policies and procedures are approved, maintained, and reviewed regularly.",
        "Documented for critical areas and reviewed periodically.",
        "Basic policies exist.",
        "Outdated or partial policies.",
        "No documented policies.",
    ]),
    "03.15.02": ("Do you maintain a current System Security Plan (SSP)?", [
        "The SSP is complete, current, and maintained as the system changes.",
        "An SSP exists and is updated periodically.",
        "A basic SSP exists.",
        "An outdated or incomplete SSP exists.",
        "No SSP.",
    ]),
    "03.15.03": ("Are rules of behavior defined and acknowledged by users?", [
        "Rules of behavior are defined, acknowledged, and re-acknowledged on change.",
        "Defined and acknowledged.",
        "Defined, but acknowledgment is inconsistent.",
        "Informal.",
        "No rules of behavior.",
    ]),
    # ── 03.16 System & Services Acquisition ───────────────────────────
    "03.16.01": ("Are security engineering principles applied when building and changing systems?", [
        "Security-by-design principles are applied and verified across the system lifecycle.",
        "Applied for critical systems.",
        "Sometimes applied.",
        "Rarely applied.",
        "Not applied.",
    ]),
    "03.16.02": ("How do you handle unsupported / end-of-life system components?", [
        "End-of-life components are tracked and replaced or mitigated proactively.",
        "Tracked for critical systems.",
        "Handled reactively.",
        "Minimal handling.",
        "Unsupported components run unmanaged.",
    ]),
    "03.16.03": ("Are external service providers' security requirements defined and monitored?", [
        "Provider security requirements are defined, contractual, and monitored.",
        "Defined for critical providers.",
        "Some requirements defined.",
        "Informal.",
        "No external-provider requirements.",
    ]),
    # ── 03.17 Supply Chain Risk Management ────────────────────────────
    "03.17.01": ("Do you have a supply chain risk management (SCRM) plan?", [
        "A maintained SCRM plan governs sourcing decisions and is reviewed regularly.",
        "A plan exists for the critical supply chain.",
        "A basic plan exists.",
        "Informal.",
        "No SCRM plan.",
    ]),
    "03.17.02": ("Are supply-chain controls applied in acquisition decisions?", [
        "Supply-chain controls and tooling are embedded in acquisition decisions.",
        "Applied for critical acquisitions.",
        "Sometimes applied.",
        "Rarely applied.",
        "No supply-chain controls in acquisitions.",
    ]),
    "03.17.03": ("Are security requirements flowed down to suppliers and verified?", [
        "Requirements are flowed down, verified, and monitored across suppliers.",
        "Flowed down to critical suppliers.",
        "Some flow-down.",
        "Informal.",
        "No flow-down of requirements.",
    ]),
}
