"""
Seed script - runs once on first startup.
Creates: EVA internal tenant, super admin user, demo users, 3 frameworks, sample controls.
"""
import asyncio
import os
import uuid
from sqlalchemy import select, text
from app.core.database import AsyncSessionLocal
from app.core.config import settings
from app.core.security import hash_password


def _write_seed_file(org_id, ref: str):
    """Write a small placeholder evidence file so demo downloads/preview work."""
    base = settings.STORAGE_LOCAL_PATH
    folder = os.path.join(base, str(org_id))
    try:
        os.makedirs(folder, exist_ok=True)
        key = f"{org_id}/seed_{ref}.txt"
        content = (
            f"EVA Cybersecurity Audit Portal - demo evidence\n"
            f"Control: {ref}\n"
            f"This placeholder file is generated by the seed script so that the\n"
            f"download and preview features are demonstrable out of the box.\n"
        ).encode()
        with open(os.path.join(base, key), "wb") as fh:
            fh.write(content)
        return key, f"{ref}_evidence.txt", len(content)
    except Exception:
        return None, None, None
# Import ALL models first so SQLAlchemy relationship registry is complete
from app.models import framework, evidence  # noqa: F401 - registers OrgControl etc
from app.models.tenant import Tenant, TenantType, SubscriptionStatus
from app.models.user import User, UserRole
from app.models.framework import Framework, Control, ControlPriority, ControlRisk, ControlCategory
from app.models.billing import BillingPlan, PlanTier
from app.models.platform import PlatformSettings, BillingMode
from app.models.evidence import (
    OrgControl, OrgControlStatus, EvidenceItem, EvidenceStatus,
    EvidenceSource, EvidenceFrequency,
)

# Evidence "best practices" per control ref - populates Control.evidence_best_practices
# (newline-joined) and drives evidence_expected on the Controls screen.
BEST_PRACTICES = {
    "AC.1.001": [
        "Include a signed, dated access control policy",
        "Export a current user roster from your identity provider",
        "Screenshot MFA enrollment for all privileged accounts",
        "Provide access log samples covering the last 90 days",
    ],
    "AC.1.002": [
        "Role-based access control policy",
        "Role matrix showing permissions per user type",
        "Evidence that overprivileged accounts were revoked",
    ],
    "IA.1.076": [
        "User account list with unique IDs",
        "No shared accounts policy",
        "Service account inventory",
    ],
    "IA.2.078": [
        "Password policy document",
        "System config showing password rules enforced",
        "Evidence of last password change cycle",
    ],
    "CM.2.061": [
        "Configuration baseline documents per system type",
        "Change management process",
        "Comparison of current vs baseline configs",
    ],
    "IR.2.092": [
        "Incident response procedure",
        "Incident register/log",
        "Contact list for escalation",
    ],
    "AU.2.041": [
        "Audit log configuration screenshot",
        "Sample log export showing user activity",
        "Log retention policy",
    ],
    "SI.1.210": [
        "Vulnerability scan report",
        "Patch management policy",
        "Evidence of patch applied within SLA",
    ],
}

# Demo org-control posture for the client tenant (NovLogix), keyed by control ref.
# Drives the dashboard's real readiness %, gaps, and status breakdown.
CLIENT_POSTURE = {
    "AC.L1-3.1.1":  OrgControlStatus.implemented,
    "AC.L1-3.1.2":  OrgControlStatus.verified,
    "AC.L1-3.1.20": OrgControlStatus.in_progress,
    "AC.L1-3.1.22": OrgControlStatus.not_started,
    "IA.L1-3.5.1":  OrgControlStatus.implemented,
    "IA.L1-3.5.2":  OrgControlStatus.in_progress,
    "MP.L1-3.8.3":  OrgControlStatus.not_started,
    "PE.L1-3.10.1": OrgControlStatus.implemented,
}


SEED_USERS = [
    {"email": "superadmin@eva.com",    "password": "demo1234", "name": "Alex Rivera",      "role": UserRole.super_admin,   "org": "EVA Technologies"},
    {"email": "auditor@eva.com",       "password": "demo1234", "name": "Dr. Chen Wei",     "role": UserRole.eva_auditor,   "org": "EVA Technologies"},
    {"email": "msp@acmemsp.com",       "password": "demo1234", "name": "Jordan Mitchell",  "role": UserRole.msp_admin,     "org": "Acme MSP Group"},
    {"email": "analyst@acmemsp.com",   "password": "demo1234", "name": "Sam Patel",        "role": UserRole.msp_analyst,   "org": "Acme MSP Group"},
    {"email": "admin@novlogix.com",    "password": "demo1234", "name": "Sarah Kowalski",   "role": UserRole.client_admin,  "org": "NovLogix Inc."},
    {"email": "it@novlogix.com",       "password": "demo1234", "name": "Tom Regan",        "role": UserRole.contributor,   "org": "NovLogix Inc."},
    {"email": "coo@novlogix.com",      "password": "demo1234", "name": "Maria Santos",     "role": UserRole.viewer,        "org": "NovLogix Inc."},
]

CMMC_CONTROLS = [
    {
        "ref": "AC.1.001", "title": "Limit system access to authorized users",
        "level": "Level 1", "domain": "Access Control",
        "priority": ControlPriority.high, "risk_rating": ControlRisk.high,
        "control_category": ControlCategory.technical,
        "description": "Limit information system access to authorized users, processes acting on behalf of authorized users, and devices.",
        "objective": "Ensure only authorized users and devices can access organizational systems.",
        "plain_language": "Think of this like a keycard system - only people with the right badge can enter. This control ensures your computer systems work the same way.",
        "mappings": {"nist_csf": ["PR.AC-1", "PR.AC-4"], "cyber_canada": ["CC-AC-01"]},
    },
    {
        "ref": "AC.1.002", "title": "Limit system access to types of transactions permitted",
        "level": "Level 1", "domain": "Access Control",
        "priority": ControlPriority.high, "risk_rating": ControlRisk.high,
        "control_category": ControlCategory.technical,
        "description": "Limit information system access to the types of transactions and functions that authorized users are permitted to execute.",
        "objective": "Ensure users can only perform actions authorized for their role.",
        "plain_language": "Users should only be able to do what their job requires - not more.",
        "mappings": {"nist_csf": ["PR.AC-4"], "cyber_canada": ["CC-AC-02"]},
    },
    {
        "ref": "IA.1.076", "title": "Identify information system users and processes",
        "level": "Level 1", "domain": "Identification & Auth",
        "priority": ControlPriority.high, "risk_rating": ControlRisk.critical,
        "control_category": ControlCategory.technical,
        "description": "Identify information system users, processes acting on behalf of users, or devices.",
        "objective": "Ensure every user and process is individually identified.",
        "plain_language": "Every person and automated process must have a unique ID. Shared accounts are not allowed.",
        "mappings": {"nist_csf": ["PR.AC-1"], "cyber_canada": ["CC-IA-01"]},
    },
    {
        "ref": "IA.2.078", "title": "Enforce minimum password complexity",
        "level": "Level 2", "domain": "Identification & Auth",
        "priority": ControlPriority.high, "risk_rating": ControlRisk.high,
        "control_category": ControlCategory.technical,
        "description": "Enforce a minimum password complexity and change of characters when new passwords are created.",
        "objective": "Prevent unauthorized access through weak or reused passwords.",
        "plain_language": "Passwords must be hard to guess: at least 12 characters, mixed case, numbers, and symbols.",
        "mappings": {"nist_csf": ["PR.AC-1"]},
    },
    {
        "ref": "CM.2.061", "title": "Establish and maintain baseline configurations",
        "level": "Level 2", "domain": "Config Management",
        "priority": ControlPriority.medium, "risk_rating": ControlRisk.medium,
        "control_category": ControlCategory.technical,
        "description": "Establish and maintain baseline configurations and inventories of organizational information systems.",
        "objective": "Prevent configuration drift and ensure systems are deployed securely.",
        "plain_language": "Create a standard, secure configuration for each type of system and document it.",
        "mappings": {"nist_csf": ["PR.IP-1"]},
    },
    {
        "ref": "IR.2.092", "title": "Track, document and report incidents",
        "level": "Level 2", "domain": "Incident Response",
        "priority": ControlPriority.high, "risk_rating": ControlRisk.high,
        "control_category": ControlCategory.administrative,
        "description": "Track, document, and report incidents to designated officials and/or authorities.",
        "objective": "Ensure incidents are detected, documented, and escalated appropriately.",
        "plain_language": "When a security incident happens, it must be logged and escalated.",
        "mappings": {"nist_csf": ["RS.CO-2"], "cyber_canada": ["CC-IR-01"]},
    },
    {
        "ref": "AU.2.041", "title": "Ensure user actions can be traced",
        "level": "Level 2", "domain": "Audit & Accountability",
        "priority": ControlPriority.medium, "risk_rating": ControlRisk.medium,
        "control_category": ControlCategory.technical,
        "description": "Ensure that the actions of individual system users can be uniquely traced.",
        "objective": "Provide accountability and forensic capability for system actions.",
        "plain_language": "Every action on the system must be logged with who did it and when.",
        "mappings": {"nist_csf": ["DE.CM-3"], "cyber_canada": ["CC-AU-01"]},
    },
    {
        "ref": "SI.1.210", "title": "Identify and manage system flaws",
        "level": "Level 1", "domain": "System Integrity",
        "priority": ControlPriority.medium, "risk_rating": ControlRisk.medium,
        "control_category": ControlCategory.technical,
        "description": "Identify, report, and correct information system flaws in a timely manner.",
        "objective": "Reduce attack surface by maintaining up-to-date, patched systems.",
        "plain_language": "When software vulnerabilities are found, fix them quickly.",
        "mappings": {"nist_csf": ["DE.CM-8"]},
    },
]


async def seed():
    async with AsyncSessionLocal() as db:
        # Check if already seeded
        result = await db.execute(select(User).where(User.email == "superadmin@eva.com"))
        if result.scalar_one_or_none():
            print("Database already seeded - skipping")
            return

        print("Seeding database...")

        # Create tenants
        tenants_map = {}
        for org_name in ["EVA Technologies", "Acme MSP Group", "NovLogix Inc."]:
            t_type = (
                TenantType.eva_internal if org_name == "EVA Technologies"
                else TenantType.msp if org_name == "Acme MSP Group"
                else TenantType.single_client
            )
            tenant = Tenant(
                name=org_name,
                tenant_type=t_type,
                subscription_status=SubscriptionStatus.active,
                plan_name="MSP Professional" if org_name == "Acme MSP Group" else "Professional",
            )
            db.add(tenant)
            tenants_map[org_name] = tenant

        await db.flush()

        # Set NovLogix parent to Acme MSP
        tenants_map["NovLogix Inc."].parent_msp_id = tenants_map["Acme MSP Group"].id
        tenants_map["NovLogix Inc."].msp_review_enabled = True

        # Create users
        for u in SEED_USERS:
            user = User(
                tenant_id=tenants_map[u["org"]].id,
                email=u["email"],
                password_hash=hash_password(u["password"]),
                display_name=u["name"],
                role=u["role"],
            )
            db.add(user)

        # Frameworks (CMMC 2.0 - Level 1/2, NIST SP 800-171 r3, ITSP.10.171)
        # are created by app.seed_catalogs, which runs BEFORE this seed. We no
        # longer create a separate demo "CMMC 2.0" framework or an empty
        # "NIST CSF" stub - the library shows only the real catalogs.
        await db.flush()

        # ── Billing plans (configurable packages) ──
        pro_plan = BillingPlan(
            name="Professional", tier=PlanTier.single_client, price_monthly=499, wholesale_monthly=349, is_active=True,
            inclusions={
                "frameworks": "all",  # CMMC, NIST CSF and Cyber Canada all available
                "features": {"reports": True, "import": False, "msp_review": False, "audit_logs": False, "api": False},
                "max_users": 10, "max_clients": 0,
            },
        )
        msp_plan = BillingPlan(
            name="MSP Professional", tier=PlanTier.msp, price_monthly=1499, is_active=True,
            inclusions={
                "frameworks": "all",
                "features": {"reports": True, "import": True, "msp_review": True, "audit_logs": True, "api": True},
                "max_users": 25, "max_clients": 50,
            },
        )
        db.add_all([pro_plan, msp_plan])
        await db.flush()
        tenants_map["Acme MSP Group"].plan_id = msp_plan.id
        tenants_map["NovLogix Inc."].plan_id = pro_plan.id
        tenants_map["NovLogix Inc."].monthly_price = 599  # retail the MSP charges this client

        # ── Two MSP examples so the margin model is visible live ──
        # Acme MSP Group → 3 active clients (NovLogix + 2) → 0% volume tier.
        #   Per client @ $599 retail, $349 wholesale → MSP margin $250, EVA net $349.
        for nm in ["Lakeside Dental", "Borealis Logistics"]:
            db.add(Tenant(
                name=nm, tenant_type=TenantType.single_client,
                parent_msp_id=tenants_map["Acme MSP Group"].id,
                subscription_status=SubscriptionStatus.active,
                plan_id=pro_plan.id, plan_name="Professional",
                monthly_price=599, msp_review_enabled=True,
            ))

        # Northpeak IT → a second MSP with 8 active clients → 5% volume tier.
        #   Per client @ $599 retail, $332 effective wholesale → MSP margin $267, EVA net $332.
        northpeak = Tenant(
            name="Northpeak IT", tenant_type=TenantType.msp,
            subscription_status=SubscriptionStatus.active,
            plan_id=msp_plan.id, plan_name="MSP Professional",
        )
        db.add(northpeak)
        await db.flush()
        db.add(User(
            tenant_id=northpeak.id, email="msp@northpeak.com",
            password_hash=hash_password("demo1234"), display_name="Riley Chen",
            role=UserRole.msp_admin,
        ))
        northpeak_clients = [
            "Imprimerie Rivard",
            "Boulangerie Saint-Laurent",
            "Transport Gagnon & Fils",
            "Clinique Dentaire Tremblay",
            "Usinage Précision Lévis",
            "Comptables Bélanger inc.",
            "Distributions Boréal",
            "Garage Mécano Drummond",
        ]
        for nm in northpeak_clients:
            db.add(Tenant(
                name=nm, tenant_type=TenantType.single_client,
                parent_msp_id=northpeak.id, subscription_status=SubscriptionStatus.active,
                plan_id=pro_plan.id, plan_name="Professional",
                monthly_price=599, msp_review_enabled=True,
            ))

        # Default platform monetization settings (EVA can change in the admin panel)
        db.add(PlatformSettings(billing_mode=BillingMode.no_card_trial, trial_days=14))

        # No demo compliance posture is seeded. Every client (NovLogix included)
        # starts empty - controls/evidence appear only once a framework is
        # assigned and real work begins. Keeps the portfolio dashboard at 0%
        # until there is genuine client data.

        await db.commit()
        print("✅ Database seeded successfully")
        print("   Demo users: superadmin@eva.com / auditor@eva.com / msp@acmemsp.com")
        print("   Password for all: demo1234")


if __name__ == "__main__":
    asyncio.run(seed())
